### ISSUE TITLE
Cant get Binary Tree to compile

### ISSUE THREAD

**Issue by axptwig** [raywenderlich/swift-algorithm-club#101]
Hey Matthijs,
I am pretty new to swift and I have been looking to contribute to this repo as a learning experience. Right now i am taking a look at the Binary Search Tree implementation and in both solution 1 and 2 when i try to compile the playground contents.swift file, it gives me and unresolved identifier error for Binary Search Tree, i was wondering if you could help me understand why this is happening/how to fix it. Thanks!
```c
Contents.swift:4:12: error: use of unresolved identifier 'BinarySearchTree'
var tree = BinarySearchTree.Leaf(7)
```
I am compiling using 
```c
swiftc Contents.swift -o out
```

**Comment by axptwig** [comment]
also could you tell me how to import the modules you used such as foundation and XCTest? I am running Ubuntu14.04 and am not exactly sure what i need to do to make these statements work.

**Comment by hollance** [comment]
The idea of a playground is that you don't need to compile it yourself. Of course, if you're running Ubuntu, then playgrounds won't work. In that case you'll have to compile Contents.swift but also Sources/BinarySearchTree.swift (from the playground folder).

Unfortunately, I have no experience with Swift on Ubuntu, so I can't really help you in more detail.
