### ISSUE TITLE
Shortest path algorithm (weighted)

### ISSUE THREAD

**Issue by leetal** [raywenderlich/swift-algorithm-club#108]
I think a weighted variant of the shortest path algorithm would fit this great repository as well. Perhaps implementing Dijkstras or Bellman-Fords (allowing negative vertices) would yield usability for people trying to learn algorithms and also want a way of calculating the shortest, most cheap path from a given node to all others.

Just a thought 👍

**Comment by hollance** [comment]
Absolutely!

**Comment by armcknight** [comment]
Just saw this, wanted to drop a note that I'm currently working on this at #112!

**Comment by chris-pilcher** [comment]
Thanks for the suggestion @leetal! I'm going to close this issue because we have a related pull request. Please feel free to raise any additional issues/suggestions for improvement!
