### ISSUE TITLE
Add unit testing

### ISSUE THREAD

**Issue by samirGuerdah** [raywenderlich/swift-algorithm-club#11]
I think that we need unit testing to validate some complicated algorithms, even the simplest ones need testing to avoid regressions. 

XCTests is not supported in playgrounds, hope that it will be in the future. 
I think that we should organize the project to have a test target.

**Comment by hollance** [comment]
Agreed. I think the simplest way to approach this is to add an Xcode project (OS X target) for the tests. It should use the existing source file.

I will add some unit tests later because I already have them for some of the algorithms.

**Comment by hollance** [comment]
OK, I've added unit tests to a number of algorithms. Anyone who is willing to write tests for the rest is more than welcome to. :-)

**Comment by samirGuerdah** [comment]
:+1:

**Comment by samirGuerdah** [comment]
I think that the best solution is to create **an independent test bundle** ( Standolone test). 
With independent tests, Test Bundle will be launched **on its own**, the application **won't be launched at all and there will only the test bundle loaded in memory**.

The inconvénients with the hosted tests ( the actual solution) : 

1. Xcode launch the application ( applicationDidFinishLaunching will be called), then Xcode loads the test bundle and finally launch the tests inside the application.
2. I think that we  don't need to have an `NSApplicationDelegate`...

An other note with the actual solution is that each algorithm has it's own target test, witch i think is not needed. We can have one test target that runs all the algorithms tests.

I can come with a solution with an independent test bundle next week if you want.

Thanks

**Comment by hollance** [comment]
That sounds good to me!

I'm not really thrilled with the current solution because of the same reasons you mention, so if you know of a better way to do it, then I'm all for it.

**Comment by johnrufusj** [comment]
I think an independent test bundle would make more sense. But if you wanted to test within individual playgrounds, I think it is feasible.  Check out this post by @sshrpe regarding TDD inside playgrounds (http://initwithstyle.net/2015/11/tdd-in-swift-playgrounds/)  It is actually quite interesting.  The only thing I don't like about the solution is not having the ability to import the test separately.   His sample on github is here: https://github.com/sshrpe/TDDSwiftPlayground

Food for thought.

**Comment by hollance** [comment]
It's an interesting idea, but I have no problem keeping the tests out of the playgrounds. Using a playground may be handy for developing new tests but in general I think tests and playgrounds serve two different purposes.

**Comment by johnrufusj** [comment]
That makes sense.

**Comment by barbaramartina** [comment]
Hi guys, I just read this conversation. I've added PR https://github.com/hollance/swift-algorithm-club/pull/46 with some unit tests for _Array2D_ and _AVLTree_. You can comment directly there with any suggestion.

**Comment by hollance** [comment]
I have changed all the unit tests to be just test bundles, without host application.

I want to keep the tests inside the folders for the algorithm it belongs to, instead of one big test project. This helps to avoid naming collisions for when multiple data structures use the same name (`TreeNode` for example).

**Comment by barbaramartina** [comment]
Cool. That make sense. I have added the main project as a possibility in the future to make some examples application with a visual feedback. But it's better to keep it simpler , +1

**Comment by chris-pilcher** [comment]
Unit tests have been added to a number of the algorithms. We will keep working to improve the test coverage. Please feel free to create issues for any specific algorithms where you think tests could be improved.
