### ISSUE TITLE
Travis CI not enabled

### ISSUE THREAD

**Issue by prankymat** [raywenderlich/swift-algorithm-club#120]
There is a link to build status at the bottom of README.md. However the link is not valid as the project is not found on Travis CI.

Is this project dropping support for Travis CI? If so please remove the build status badge. Thanks!

**Comment by chris-pilcher** [comment]
Thanks! This has been fixed in #115.

This project is not dropping support for Travis CI. The repository was moved from github.com/hollance/swift-algorithm-club to github.com/raywenderlich/swift-algorithm-club which broke the build status badge.
