### ISSUE TITLE
Super cool, maybe add to hackerrank.com

### ISSUE THREAD

**Issue by madhavajay** [raywenderlich/swift-algorithm-club#123]
This is really cool, do you think it would be nice to add all of these to a hackerrank.com as a challenge so that people can work on them and keep score using the hackerrank.com system?

**Comment by chris-pilcher** [comment]
Thanks for the suggestion! This looks like a really useful site. We're pretty busy trying to get the repository into a clean state at the moment. Once that's done we will have a look into hackerrank.
