### ISSUE TITLE
Code snippets for simply drag&drag algorithms and data structures 

### ISSUE THREAD

**Issue by barbaramartina** [raywenderlich/swift-algorithm-club#129]
Hi guys, I've added to my personal collection, some data structure and algorithms as code snippets. 
https://github.com/barbaramartina/swift-code-snippets/commit/49572e01161ded6e53a58c01753f2b4ca4645981
I was thinking if code snippets could be added to this repo, and how useful it would be. Due to probable changes in the implementations, if we don't have the snippet generation done automatically, the sync between algorithms/snippets can be easily lost. 
Anyway, I think having the snippets prepared to be imported into any other XCode could be great.  
In this line of thoughts, I was considering including some kind of MARKUP... like:  
**// \<snippet\>  
// \</snippet\>**  

In the part of the code that we would like to have automatically converted to code snippets.  
That way we could prepare an script later to parse all the **.swift** file and load the snippets content.

**Comment by kelvinlauKL** [comment]
Sounds like a great idea for a future update 👍 Thanks for bringing it up @barbaramartina!

**Comment by barbaramartina** [comment]
I'm open to discuss/ analyze / implement alternatives for achieving that any time. Just let me know. For the moment I'll keep updating my collection with the other algorithms.
