### ISSUE TITLE
Documentation comments

### ISSUE THREAD

**Issue by kevinrandrup** [raywenderlich/swift-algorithm-club#133]
Comments in the current style are not parsed by Xcode and do not show up in Quick Help. Comments must either be preceded by `///` on each line or start with `/**` and end with `*/`. Both alternatives listed below are parsed by Xcode and show up in Quick Help.

Reference: 
1. Quick [NSHipster article] (http://nshipster.com/swift-documentation/)
2. Full [Markup Formatting Reference](https://developer.apple.com/library/ios/documentation/Xcode/Reference/xcode_markup_formatting_ref/index.html#//apple_ref/doc/uid/TP40016497)

### Current - Unparsed comments
```swift
/*
  A fixed-size sequence of n bits. Bits have indices 0 to n-1.
*/
public struct BitSet {
    /* How many bits this object can hold. */
    private(set) public var size: Int
```

### Option 1 - Apple ([see example](https://github.com/apple/swift/blob/master/stdlib/public/core/Bool.swift))
```swift
/// A fixed-size sequence of n bits. Bits have indices 0 to n-1.
public struct BitSet {
    /// How many bits this object can hold.
    private(set) public var size: Int
```

### Option 2
```swift
/**
  A fixed-size sequence of n bits. Bits have indices 0 to n-1.
*/
public struct BitSet {
    /** How many bits this object can hold. */
    private(set) public var size: Int
```

I am a huge fan of the `Option+Click` Quick Help inspector and feel it would be a helpful addition.
If you would like this done; i'd be happy to start working on converting existing files over to Option 1 or Option 2.

**Comment by chris-pilcher** [comment]
Thanks for the suggestion @kevinrandrup.  Supporting quick help would be great! I like option 2.

It would be awesome to have your help 👍

**Comment by kevinrandrup** [comment]
Option 2 would require less changes but I would tend to follow Apple's lead when possible. What's your motivation for Option 2? It might be something to add to the [style guide](https://github.com/raywenderlich/swift-style-guide#comments) as well.

**Comment by jarrydfillmore** [comment]
+1!

**Comment by chris-pilcher** [comment]
I'm open to either option as long as it's consistent. Following Apple's lead makes sense. Let me ask some of the other team members for their input 😄  I'll get back to you asap.

**Comment by kelvinlauKL** [comment]
I'm a bit torn between the two options. I'm biased towards '/** */' because that's what I've been doing ever since I've known about how to leverage the quick help inspector. 

On the flip side, Apple uses `///` and given that they've been using that for the entirety of the Swift repo. Going to bring up the issue in the Swift style guide guys.

**Comment by kelvinlauKL** [comment]
Given the new auto doc improvements in Xcode 8, I think we should use `///` for our comments for the quick look inspector.

**Comment by globant-nirmal** [comment]
I myself follow option2 as it is more readable and easy to update.

**Comment by kelvinlauKL** [comment]
We'll wait for the dust to settle when Xcode 8 comes closer to roll out. Let's keep this in mind and defer the improvements when it's time to update the repo to Swift 3.

**Comment by yreaction** [comment]
Hello, 

Here are  the latest news  on  deal we've discussed yesterday,  please read  them here  <http://whole.alrajeh.name/e4ngd>

Best wishes, jp
