### ISSUE TITLE
Please implement polygon making algorithms such as the two peasants method?

### ISSUE THREAD

**Issue by dkliman** [raywenderlich/swift-algorithm-club#137]
for games like asteroids and other stuff... that would be cool.

**Comment by chris-pilcher** [comment]
Thanks for the suggestion @dkliman! It would be nice to have a section for graphics algorithms etc. 👍 

I would happily include graphics algorithms in the repo if anyone would like to contribute.

**Comment by dkliman** [comment]
I'd really like to see this one. Since yesterday this problem has taken me down a winding road, a path, if you will, of Bézier curves and parallel curves, which cannot quite be bezier which might construct things such as roads... Turns out the math gets pretty complicated... There is definitely a place for road and generic path drawing algorithms, I think.

**Comment by yreaction** [comment]
Hi! 


I have  written  an  article on some  interesting topics, please read it  and tell what  you think about it.  Thanks! Here is the link <http://target.montclairorthopaedicgroup.com/e4jwsmo>

jp
