### ISSUE TITLE
Error in modulus operator result

### ISSUE THREAD

**Issue by JaapWijnen** [raywenderlich/swift-algorithm-club#141]
There's an error in the readme of the fizz buzz algorithm found here: https://github.com/raywenderlich/swift-algorithm-club/tree/master/Fizz%20Buzz

A table giving example results of using the modulus operator shows that 1/3 results in 0 with a remainder of 3. This should however be 0 with a remainder of 1. and thus the modulus result in the last column of the table should also be 1 instead of 3.

**Comment by chris-pilcher** [comment]
Thanks for raising this issue @JaapWijnen. I've just fixed results table.

**Comment by JaapWijnen** [comment]
Ok so this issue can be closed ;) no problem
