### ISSUE TITLE
Manacher’s Algorithm -- Swifty Implementation

### ISSUE THREAD

**Issue by Jxrgxn** [raywenderlich/swift-algorithm-club#147]
I want to contribute my Swifty implementation of [Manacher's Algorithm](https://en.wikipedia.org/wiki/Longest_palindromic_substring) . I searched and didn't seem to find anything in the code--but I've been wrong many times before.

**Comment by chris-pilcher** [comment]
Sounds like a great idea @Jxrgxn! It would be great to have this algorithm included in the repo. 👍  

Take a look at the [how to contribute](https://github.com/raywenderlich/swift-algorithm-club/blob/master/How%20to%20Contribute.markdown#please-follow-this-process) page for instructions on including a new algorithm.

**Comment by chris-pilcher** [comment]
I'm going to close this issue because PR #149 has been opened. Thanks!

**Comment by yreaction** [comment]
Hey, 

I've  gathered  some  interesting information,  just take a  look, it  may be  helpful for you. You may read  it here <http://expert.alrajeh.name/e4rfxkyk>

Sent from a prehistoric stone tablet, jp
