### ISSUE TITLE
Binary Indexed Tree (Fenwick Tree)

### ISSUE THREAD

**Issue by farzadshbfn** [raywenderlich/swift-algorithm-club#153]
Since you've added SegmentTree, I think it's good to add [Fenwick](https://en.wikipedia.org/wiki/Fenwick_tree) too, they differ on speed and some usages.

**Comment by chris-pilcher** [comment]
Thanks for the suggestion @farzadshbfn! 👍 I would be happy to include the Fenwick Tree data structure in the repo if anyone would like to contribute.

**Comment by farzadshbfn** [comment]
I'd give it a try ;)... it's not the code that needs time... it's ReadMe 🙃
