### ISSUE TITLE
I want find middle ( or more close to middle) value not median value. is this exist?

### ISSUE THREAD

**Issue by singcodes** [raywenderlich/swift-algorithm-club#155]
let a = [11.0, 2.0, 5.0, 9.0, 10.0, 10.0, 1.0]
a's median value is 9.0
but that's not my purpose, I want find value the most close to middle value between 11.0 and 1.0, and it would be 5.0

Is this exist algorithm?
If may not being. I want update that.

**Comment by chris-pilcher** [comment]
Hi @singcodes, 

Could you calculate the mean of `a` and then find the element in `a` that is closest to the calculated mean? E.g.

```swift
let items = [11.0, 2.0, 5.0, 9.0, 10.0, 10.0, 1.0]

// Use reduce function to sum all the items together then divide by the count
let mean = items.reduce(0.0, combine: +) / Double(items.count) // 6.857142857142857

// Enumerate through all the items and find which item is closest to the mean
let closestItem = items.enumerate().minElement { abs($0.1 - mean) < abs($1.1 - mean) }!

print(closestItem.element) // 5.0
```

**Comment by singcodes** [comment]
😆 yeah, that's right. thanks! @chris-pilcher.
