### ISSUE TITLE
Why are Queue and Deque implemented using an array, rather than two stacks?

### ISSUE THREAD

**Issue by timvermeulen** [raywenderlich/swift-algorithm-club#159]
The Deque page even mentions that a deque can also be implemented using two stacks rather than one array. Using two stacks is a lot easier because you don't have to deal with getting rid of empty space at the front, and I bet that makes it faster as well. What's the point of using a single array?

**Comment by hollance** [comment]
Simplicity. Queue and Deque are abstract datatypes, so they can be implemented in many different ways. It doesn't get much simpler than using an array.

That said, feel free to contribute a version that uses two stacks. :-)

**Comment by timvermeulen** [comment]
The naive implementations using an array are simplistic for sure! But I wouldn't really call the more efficient implementations simplistic. 😜 They keep track of the index of the first element and they need logic for removing unused space.  Using two stacks is definitely more simplistic than that.

**Comment by kelvinlauKL** [comment]
We're always looking for contributors @timvermeulen :)

**Comment by Adekunle77** [comment]
Hi there I am just started to learn Swift. Do you think swift-algorithm would be too advanced for me?
