### ISSUE TITLE
swift-algorithm, is it for beginners?

### ISSUE THREAD

**Issue by Adekunle77** [raywenderlich/swift-algorithm-club#160]
Hi there I am just started to learn Swift. Do you think swift-algorithm would be too advanced for me?

**Comment by Jxrgxn** [comment]
Nope. There's stuff as simple as linked-lists and the two-sum problem to
all the way to AVL Trees. Give it a shot!
ᐧ

**Comment by Adekunle77** [comment]
Where do I start? Or how do I use it?

**Comment by kelvinlauKL** [comment]
There are a few data structures that serve as a basis to many others:

* stacks
* queues
* trees
* linked lists

For beginners, understanding those should be regarded as a prerequisite to most of the other articles. 

Some of the articles are pretty advanced in the sense that the authors uses some relatively advanced Swift operations that I would not expect a beginner to understand, but googling them should easily give you some things to read about :)

**Comment by grantkemp** [comment]
I agred - Can I suggest that we have a basic Section labelled for Beginners   ( maybe a folder) and we have some tests in there so we can let users test various scenarios.
