### ISSUE TITLE
access rights of array vaiable

### ISSUE THREAD

**Issue by mayurtolani** [raywenderlich/swift-algorithm-club#169]
why is it that i can access, array variable outside the class?
I am new to swift, but when i was in java, i coudn't access a private variable outside the class.
here, in playground, i am using the array variable and functions like popLast() in Queues which completely looses the meaning of a Queue.
`var que = Queue<String>()`
`que.enqueue("Mayur")`
`que.enqueue("Tolani")`
`que.array //this is private, it should give an error`
`que.array.popLast()//this shouldn't be allowed, right?`

**Comment by Jxrgxn** [comment]
I reckon struct versus class diff

**Comment by hollance** [comment]
`public` and `private` work differently in Swift than in Java.
