### ISSUE TITLE
Merge sort can be further optimized.

### ISSUE THREAD

**Issue by madnik** [raywenderlich/swift-algorithm-club#170]
I tried to implement merge sort manipulating original array itself rather than allocating new arrays within sub problems. 

https://gist.github.com/madnik/924168b045f57f94183908a0bc1010e9

Appreciate discussion and conclude the best.

**Comment by hollance** [comment]
You say "optimized" but what exactly do you mean by that?

You have made the merging in-place so it only uses one array, but your merge operations do:

```
array.insert(array.removeAtIndex(q+1))
```

The time complexity for `array.removeAtIndex()` and `array.insert(atIndex)` is O(n), not O(1). So you've traded space for time. 

In other words, your implementation uses less space but more time. It is more optimized in space use but less optimized in running time.

**Comment by madnik** [comment]
Sorry for issue subject not being descriptive enough.

Thanks for pointing out the complexity of removeAtIndex() and insert methods. Shifting elements make the complexity O(n)
