### ISSUE TITLE
Ambiguous reference to member 'init' at line:12 in HashTable.playground

### ISSUE THREAD

**Issue by EvoIos** [raywenderlich/swift-algorithm-club#175]
When I open the playground of HashTable.playground in Xcode 8 beta 3 , It produce many errors.
error:
![image](https://cloud.githubusercontent.com/assets/12396910/17431761/25f0d11a-5b2e-11e6-96ed-9139c412c30a.png)

I don't know how to solve it. Some can help me.

Thank you!

**Comment by hollance** [comment]
I think the name of this init method got changed. Try: `buckets = .init(repeating: [], count: capacity)`.

**Comment by EvoIos** [comment]
@hollance Thank you. 
The problem is array's initialization. 
In swift 3, array init style like this:
```swift
buckets = .init(repeatElement([], count: capacity))
```
