### ISSUE TITLE
Binary Search Tree RemoveChildWith2Nodes - The condition right===successor will never happen

### ISSUE THREAD

**Issue by prolificcoder** [raywenderlich/swift-algorithm-club#188]
Based on the way the code for the RemoveChildWith2Nodes, the condition right === successor will never happen. We first call successor.remove() before updating the successor's right and left positions. The remove() call initially, will ensure that if successor was indeed same as the right, its parent's right is set to nil. So this check is moot as there is no way that the right can be exactly same as successor

I will try to give a better explanation if this isn't sufficient soon.

**Comment by kelvinlauKL** [comment]
@vincentngo Could you give this a check?

**Comment by kelvinlauKL** [comment]
I gave this a look, it seems like `right === successor` is still valuable. This logic evaluates true if `right` is a leaf node. 

Even if `parent.right = nil` statement is made, `successor` is not yet removed from memory. 

Feel free to reopen this if you still think there's a mistake.
