### ISSUE TITLE
Convex Hull or QuickHull algorithm

### ISSUE THREAD

**Issue by dndydon** [raywenderlich/swift-algorithm-club#202]
I'd love to see a Swift treatment for QuickHull:  Compute the convex hull of a set of three dimensional points. Which is useful for computing volumes of convex polygons.

The algorithm is a three dimensional implementation of Quickhull, as described in Barber, Dobkin, and Huhdanpaa http://citeseer.ist.psu.edu/viewdoc/summary?doi=10.1.1.117.405&rank=4 "The Quickhull Algorithm for Convex Hulls'' (ACM Transactions on Mathematical Software, Vol. 22, No. 4, December 1996), and has a complexity of O(n log(n)) with respect to the number of points. 

A well-known C implementation of Quickhull that works for arbitrary dimensions is provided by http://www.qhull.org

Carl Wieland has contributed a Swift 2.3 QuickHull implementation here: https://github.com/utahwithak/Swift-Quickhull

**Comment by kelvinlauKL** [comment]
Added this to a Wishlist #317. Thanks @dndydon!
