### ISSUE TITLE
Search issue in Heap.swift 

### ISSUE THREAD

**Issue by alexandrutomescu** [raywenderlich/swift-algorithm-club#204]
What a gem of a repository! 
What is the purpose of
`if isOrderedBefore(element, elements[i]) { return nil }`
on line 221 of **Heap/Heap.swift** ? 
Shouldn't it be removed?

**Comment by kelvinlauKL** [comment]
It looks like the purpose of that line is to allow for an early return. 

Since the heap guarantees that the parent is always greater(max heap) or lesser(min heap) than it's children, once `isOrderedBefore` returns true, there's no point in searching further.

**Comment by alexandrutomescu** [comment]
Thanks! You are right, that's a good point.

My problem was: the heap was storing pairs (key, value) (a min heap on value), and I was searching it for a pair (x,val) with val being a dummy value. So val was interfering with that condition.
