### ISSUE TITLE
Existing Red-Black tree algorithm doesnt work properly

### ISSUE THREAD

**Issue by JaapWijnen** [raywenderlich/swift-algorithm-club#206]
Hi, I was looking around for a Red Black tree data structure in swift and came upon the one included in the swift algorithm club. After some testing though I found out that deletion isn't implemented properly.
I've now written my own version and thought of sharing it. Not too used to collaborating in these kind of projects and especially since it's not just a patch but a complete rewrite how should i go around and submit it?

**Comment by kelvinlauKL** [comment]
Thanks for pointing that out. Could you put in a pull request with the name "Red Black Tree 2"?
