### ISSUE TITLE
Links to the algorithms are mostly broken

### ISSUE THREAD

**Issue by ccarnino** [raywenderlich/swift-algorithm-club#209]
Hello.
I was reading the README file and checking out the link to the different algorithms. But are mostly broken.

For example the starter list has no links working:
```
- Stack
- Queue
- Insertion Sort
- Binary Search and Binary Search Tree
- Merge Sort
- Boyer-Moore string search
```

When opening them you get the Github 404 page. The urls are pointing to the wrong path.
Bye

**Comment by hollance** [comment]
Strange. Something must have changed with how GitHub renders the links from the Markdown files.

**Comment by kelvinlauKL** [comment]
Noted

**Comment by ccarnino** [comment]
I hope to have been helpful.
Bye

**Comment by kelvinlauKL** [comment]
Thanks for bringing it up. It was a GitHub issue and it's been fixed!
