### ISSUE TITLE
Are we using Generics only because we can use string,Int or Bool in Array?

### ISSUE THREAD

**Issue by ritesh124** [raywenderlich/swift-algorithm-club#210]
i mean can some one please elaborate it in some more details 
logic is okay but how come this is the best way of linear search
T stand for generic item in Argument (may i know what does it mean when we use it by function name)

Thanks

**Comment by kelvinlauKL** [comment]
"Are we using generics only because we can use string, Int, or Bool in Array?"

- Yes

The biggest reason you'd want to use generics is to promote code reusability. In the case of `Linear Search`, using or not using generics doesn't really affect performance for the most part.
