### ISSUE TITLE
Haversine Distance

### ISSUE THREAD

**Issue by jejernig** [raywenderlich/swift-algorithm-club#244]
Anyone have a good swift 3 Haversine distance algorithm?

If your unsure what the Haversine formula does then I can briefly explain. It's used in navigation to find the distance between two points on a sphere (the earth) of latitude and longitude. I am basically going to implement this into MapKit to find the distance between my location and an alert on a map.

**Comment by JaapWijnen** [comment]
Implemented this with #255

**Comment by kelvinlauKL** [comment]
@jejernig Seems like @JaapWijnen has you covered 👍
