### ISSUE TITLE
Epub?

### ISSUE THREAD

**Issue by aquarchitect** [raywenderlich/swift-algorithm-club#245]
I love the idea of learning more about algorithm with my favorite language while commuting; so I put together this automatic process generating an ePub file using _Pandoc_ and _Travis CI_. It is still an early WIP; I hope that the screenshot will paint you a picture of what I am trying to do. 

![screen shot 2016-09-28 at 5 24 00 pm](https://cloud.githubusercontent.com/assets/8365795/18936915/84ec7254-85a0-11e6-8e71-fc7cb8a4925e.png)

I only have few algorithms in the ebook so far because I sort it manually by the topics (from README page). You can download and check out the ebook [here](https://github.com/aquarchitect/swift-algorithm-club/releases/download/1.0.0/SwiftAlgo.epub).

I plan making it look nicer with a cover and syntax highlighting.
I'd love to hear your thoughts @kelvinlauKL @chris-pilcher.

**Comment by kelvinlauKL** [comment]
Really cool. //cc @chris-pilcher

**Comment by briancordanyoung** [comment]
@aquarchitect What happened to this pub work?  Did you get any auto generation working? I'd love to understand Pandoc well enough and make sure the epub can be generated.  Are there any scripts?

**Comment by aquarchitect** [comment]
Hey @briancordanyoung,

I've tried both __Pandoc__ and __Calibre__ to generate ePub from Markdown, but they don't look good. 
- __Pandoc__ renders the code block nicely with monospace font, but it's missing the code highlight. I read some where that it currently does not have support for Swift highlight.
- __Calibre__ renders the code block with syntax highlight, but the font all appears very weird.

[This __GitHub__ page](http://raywenderlich.github.io/swift-algorithm-club/) is the result of my second attempt of making something easy to navigate and to read these algorithm articles. My thinking logic was that eventually I figured out how to use __Pandoc__ /__Calibre__ to convert HTML to ePub.

You can checkout the ongoing discussion at #647.
