### ISSUE TITLE
Invalid Binary Search Tree

### ISSUE THREAD

**Issue by joligario** [raywenderlich/swift-algorithm-club#246]
While reading the Binary Search Tree Readme, in the Solution 1 deleting a node section, there is an issue with

swift-algorithm-club/Binary Search Tree/Images/MinimumMaximum.png

Node 6 should not be right of node 7. One fix would be to swap 6 and 7. Another fix is to bump 6 to become 8 and increase all other nodes on right side of tree increased. Yet another fix is to move 6 to right leaf of 5. Second fix seems least destructive to text body. Either way, text body must also be changed to match new tree.

Edit: This is assuming the order of the nodes is related to their values consistent with the rest of the examples.

**Comment by kelvinlauKL** [comment]
@joligario 

Good catch!
