### ISSUE TITLE
B-Tree README typo

### ISSUE THREAD

**Issue by Zach41** [raywenderlich/swift-algorithm-club#254]
I recently read about the article of B-Tree, and in the `Moving a key to child` section, the article said that

```
(If c1 is non-leaf) We move the last children from c1 to c2's children array at index 0.
```

According to the context, I think it should be moving the last children from c2 to c1's children array at index 0.

Also, in the section `Merging two nodes`, the article said if `c1` had left sibling, 

```
3. We remove the children at index i from the parent node.
```

 According to the context, I think it should be remove the children at index `i-1`.

**Comment by ViktorSimko** [comment]
Thanks!
