### ISSUE TITLE
Duplicate code in Boyer-Moore String Search.md

### ISSUE THREAD

**Issue by LinShiwei** [raywenderlich/swift-algorithm-club#284]
In [Boyer-Moore String Search.md](https://github.com/raywenderlich/swift-algorithm-club/tree/master/Boyer-Moore), the code of Boyer-Moore-Horspool algorithm is the same as that of Boyer-Moore algorithm. It doesn't show the difference in how to check partial matches.

**Comment by hollance** [comment]
Also, for some reason the code formatting is all messed up. :-(

**Comment by mmazzei** [comment]
Hello, I just fixed it in https://github.com/raywenderlich/swift-algorithm-club/pull/330
