### ISSUE TITLE
Struct vs Class

### ISSUE THREAD

**Issue by wangshengjia** [raywenderlich/swift-algorithm-club#285]
Watching the implementations in the repo, it seems to me that most of them prefer to use `class` instead of `struct` when dealing with a data structure. Ex: `Tree`, `LinkedList`, etc...

I'm wondering why not align with built-in collections, they are all structs. Is there a specific reason or something I might miss ?

Thanks a lot.

**Comment by hollance** [comment]
The big idea behind trees, linked lists, etc is that of references (or pointers). In Swift, the only way to use references is to use classes.

It *is* possible to write a tree, list, etc with structs or enums (and we do include examples of this) but in my opinion, the most important take-away from these data structures is the concept of linking things using a reference (or a pointer).

**Comment by wangshengjia** [comment]
Yeah, I get your point. From a perspective of learning/discussing algorithm, `class` is better.

Thanks.
