### ISSUE TITLE
Concurrent version of algorithms.

### ISSUE THREAD

**Issue by dydus0x14** [raywenderlich/swift-algorithm-club#286]
What about parallel implementation of some algorithms? Are you going to do it?

Some methods can be parallel and it's for free, for example, Floyd-Warshall. On iOS there is a bunch of abilities to implement it (libdispatch, directly with threads...). We can compare different versions and find the most effective ways :)

**Comment by kelvinlauKL** [comment]
Planning to do some refactoring on a few algorithms in the future. Will keep this in mind... 

I once tried to do a parallelized `flatMap`, was fun but never got it working properly :]
