### ISSUE TITLE
Which data structure should I use for lots of insertions, and lots of reads, if reads must access the data in an ordered fashion?

### ISSUE THREAD

**Issue by ugultopu** [raywenderlich/swift-algorithm-club#296]
I can't find what data structure should I use to most efficiently handle my app's functionality. Here's the scenario:

I am making a tracking app. In the app, clients continuously send their location (a CLLocationCoordinate2D) and the timestamp associated with this location to a server. And the server continuously distributes this data to trackers.

As an example, let's say Alice, Bob, Mike and Mary are users of this app. The app continuously sends the aforementioned data to the server. Let's say Alice tracks Bob and Mary. Then server distributes the data which it received from Bob and Mary to Alice.

When the app at Alice's device receives this data, it:
1) Groups them by user (that is, partitions the data as Bob's and Mary's data).
2) Sorts them according to their timestamp.
3) Draws a custom overlay (a line) on the map which shows where the respective users have been.

As you can observe, there is a continuous insertion of data. And there is also a continuous read of this data, because the overlay will continuously be (re)drawn on the map.

Considering there will be a constant read of data (because the overlay will continuously be redrawn on the map), I have thought that the most efficient way of doing this is using a data structure which keeps an order at all times. This way, each new element will be inserted at the correct place and be simply drawn without any further sorting operation.

For this, I have checked out Ordered Array and Ordered Set. However, both of them state that if insertions are common, these data structures may not be the most suitable ones. However, I am not sure if using a plain array and sorting the array at each redraw (which will happen _constantly_) would be more efficient. To me, it feels like it would be _a lot_ more inefficient. Hence, I feel like I should use a data structure which maintains the order at all times.

What kind of solution should I follow here?

Thank you very much

**Comment by hollance** [comment]
I would try the simplest approach that works first (a regular array probably). If that is a slow solution, I'd try to find a faster one. But often the simple approach is fast enough.
