### ISSUE TITLE
Remove function is wrong for some cases of Binary Search Tree Solution 1

### ISSUE THREAD

**Issue by djsison** [raywenderlich/swift-algorithm-club#309]
Consider the following tree:
> (5) <- 10 -> ((12) <- 15 -> (20 -> (22)))

which was created using the following lines of code:
```
let tree = BinarySearchTree<Int>(value: 10)
tree.insert(value: 5)
tree.insert(value: 15)
tree.insert(value: 12)
tree.insert(value: 20)
tree.insert(value: 22)
```

If I remove the node with value 15 using the following code:
```
if let toRemove = tree.search(value: 15) {
    toRemove.remove()
}
print(tree.description)
```
I get the following result:
> (5) <- 10 -> ((12) <- 20)

As you can see, the node with value 22 is now gone!

**Comment by kelvinlauKL** [comment]
Checked this, confirmed to be a bug.

**Comment by kelvinlauKL** [comment]
I've added this to a list of bugs at #316. Thanks @djsison!
