### ISSUE TITLE
The Galil and Good Suffix Rules for Boyer–Moore

### ISSUE THREAD

**Issue by Frizlab** [raywenderlich/swift-algorithm-club#312]
Hello,

I’ve done [some digging](https://en.wikipedia.org/wiki/Boyer–Moore_string_search_algorithm) about Boyer–Moore.
I quite new to this algorithm, so maybe I’m wrong, but the implementation in this repo neither contains the Good Suffix nor the Galil rules, does it?

I have two questions:
- Does it change the performance much?
- Is it planned to implement it?

Thank you

PS: Big fan of this repo! Great work, excellent initiative! 😊

**Comment by kelvinlauKL** [comment]
Hey,

The plan is to implement all things! But no, there's no specific plans to implement the Good Suffix or Galil rules - but if you're interested, we'll review it if you implement it and give some feedback 👍 

Cheers!

**Comment by kelvinlauKL** [comment]
Added this to a Wishlist. Thanks @Frizlab!

**Comment by kelvinlauKL** [comment]
Reopening for Hacktoberfest contributions!

**Comment by JaapWijnen** [comment]
The version we have now is in fact an implementation of the Boyer-Moore-Horspool algorithm. I could make a PR to rename it and remove the optionality of applying the Horspool improvement. Then if I can find some time I'll make the Boyer-Moore including Galil implementation. What do you think @kelvinlauKL ? see https://en.wikipedia.org/wiki/Boyer–Moore–Horspool_algorithm for the difference

**Comment by JaapWijnen** [comment]
Have been playing around with it a bit. But I have to say due to the way that strings are implemented in Swift it isn't easy to implement these elegantly. Unfortunately I don't have the time to really dig into it anytime soon. So if anyone else is interested go ahead!

**Comment by kelvinlauKL** [comment]
Thanks @JaapWijnen :)

**Comment by kelvinlauKL** [comment]
Closing inactive issues 👍
