### ISSUE TITLE
Contributing Guidelines PR and branding process

### ISSUE THREAD

**Issue by lostatseajoshua** [raywenderlich/swift-algorithm-club#327]
## Issue
The contributing guidelines is missing the PR and branching process.

## Resolution
The guidelines should contain what branch to create PR's against. 
Example: `your branch -> master`
It can also be extended to have different PR processes for different development in parallel. Example: 
All swift 3 contributions
`branch from swift3 -> fixes -> merge back to master`
This is just an example and doesn't reflect the current branches, but this way there could be separate work going if needed such as when Swift 4 is released or minor 3.x swift versions.

Also a branching process would be helpful if there is a flow to follow such as:
`branch from master -> create branch with a specific naming convention -> commit work -> PR back to master`

Let me know what everyone's thoughts are on this. I can own completing the task if needed.

**Comment by kelvinlauKL** [comment]
// cc @chris-pilcher @vincentngo

**Comment by lostatseajoshua** [comment]
I actually just ran into an issue with this when opening a PR. I had to fork the repo first the make my changes there and make the PR against with that fork. It would be convenient to have that process for others to know that are starting to contribute to the project.

**Comment by kelvinlauKL** [comment]
Archiving to #317
