### ISSUE TITLE
Missing a .github folder for templates.

### ISSUE THREAD

**Issue by lostatseajoshua** [raywenderlich/swift-algorithm-club#329]
## Issue
Missing .github folder for automatic templating supported by Github

## Solution
Create a .github folder to place a template for issues, contributing, and pull requests.
The templates can be designed to best fit the repo standards and can help the flow of contributing. 

#### Other
[Git template feature](https://github.com/blog/2111-issue-and-pull-request-templates)

**Comment by kelvinlauKL** [comment]
Interesting! // cc @chris-pilcher @vincentngo

**Comment by lostatseajoshua** [comment]
I have an example of this in one of my projects. If you open a PR it auto fills it out. Really nice! 
[Example PR template](https://github.com/lostatseajoshua/Challenger/blob/master/.github/PULL_REQUEST_TEMPLATE.MD)

**Comment by kelvinlauKL** [comment]
Archiving this via #317
