### ISSUE TITLE
Don't use random()

### ISSUE THREAD

**Issue by grosch** [raywenderlich/swift-algorithm-club#340]
You shouldn't really ever call random().  You should be using arc4random_uniform instead.   You are using this in the Shuffle example, and I'm guessing elsewhere too.

**Comment by hollance** [comment]
The random() function that is being used is defined as:

```
public func random(_ n: Int) -> Int {
  return Int(arc4random_uniform(UInt32(n)))
}
```

**Comment by grosch** [comment]
Only if you do that yourself.  Most people are going to look at a single algorithm and not take all the files.  If I just look at Shuffle it is standalone code.  I wouldn't know to go grab that random definition from wherever you put it.

**Comment by grosch** [comment]
OK, I found it.  You defined it in the playground, but not the main file that people are looking at.
