### ISSUE TITLE
Don't check value on Shuffle

### ISSUE THREAD

**Issue by grosch** [raywenderlich/swift-algorithm-club#341]
In the shuffle algorithm, where you implement the Fisher-Yates thing, you're checking whether i is equal to j before calling swap.

Suggest you not do this for the simple fact that swapping if they're equivalent is perfectly acceptible and that's ONE operation if it happens, vs. the cost of checking i vs. j on every single iteration through the loop.  On very large lists (which is your argument for using most of these) that will improve speed.

**Comment by donald-pinckney** [comment]
Actually, I believe that the current implementation is correct, and your suggested change is not quite correct. Intuitively I would agree with you, except that the declaration from the Swift standard library is:
```swift
/// Exchange the values of `a` and `b`.
///
/// - Precondition: `a` and `b` do not alias each other.
public func swap<T>(_ a: inout T, _ b: inout T)
```
Unfortunately, it does not sound valid to swap them at the same index.

**Comment by kelvinlauKL** [comment]
@grosch I concur with @donald-pinckney. Also did a quick check on the `swap` function to confirm:

```
var array = [1, 2]
swap(&array[1], &array[1]) // fatal error: swapping a location with itself is not supported
```
