### ISSUE TITLE
Contributing to 'Big O Notation' Documentation

### ISSUE THREAD

**Issue by saru2020** [raywenderlich/swift-algorithm-club#342]
Hi,

[This](https://www.interviewcake.com/article/python/big-o-notation-time-and-space-complexity?) is the best article that explains Big O Notation in a concise way. Would be great, if those information is available in here for Integrity.

Thanks!

**Comment by kelvinlauKL** [comment]
Heya,

We have a basic explanation of Big O Notation [here](https://github.com/raywenderlich/swift-algorithm-club/blob/master/Big-O%20Notation.markdown). Feel free to improve upon it (in your own words!).

Going to add this to the Wishlist. Feel free to make a pull request if you want to add to anything in the repo!
