### ISSUE TITLE
is it possible to store a memory address of a pointer in HashTable using swift?

### ISSUE THREAD

**Issue by DESHPANDE-1986** [raywenderlich/swift-algorithm-club#354]
i have a linked-list 1->2->3->4->5 given pointer as p at the start of a node, and i want to store the memory address of each node for which p is pointing to in a hashtable, while traversing through the list.
can you please share some of your thoughts on how can i achieve this in swift?
it will be helpful for me to find one of the way to check if linked list has loop or not.

**Comment by kelvinlauKL** [comment]
```
let object = Foo()

withUnsafePointer(to: &object) { address in
}
```

**Comment by DESHPANDE-1986** [comment]
just tested it, but some times it says "cannot pass immutable value as argument" ..

**Comment by kelvinlauKL** [comment]
I was hasty - this only works on mutable objects. I changed the `let` declaration to `var`. 

Here's a relevant SO question: http://stackoverflow.com/questions/24058906/printing-a-variable-memory-address-in-swift
