### ISSUE TITLE
Show path to Node

### ISSUE THREAD

**Issue by magonicolas** [raywenderlich/swift-algorithm-club#359]
Hello There, this algorithm is just what Im looking for, but I have an issue, and would be great if someone can help me.
For Example, from node a to h the distance is 3. Is there A Way to know which is the path of that distance? 
Maybe just printing A B E H would help for what I need!

**Comment by vincentngo** [comment]
@magonicolas i believe `func path(to: Vertex<T>, inGraph graph: AbstractGraph<T>) -> [T]?`
provides this for you.  You can just loop through it to print the nodes?

**Comment by magonicolas** [comment]
@vincentngo Thanks, but  there is no func path(to... on Shortest path. I have seen than function on SSSP, but that algorithm pass from all nodes, I need the shortest between 2 points.

**Comment by vincentngo** [comment]
@magonicolas check this one out: https://github.com/raywenderlich/swift-algorithm-club/tree/master/All-Pairs%20Shortest%20Paths

**Comment by magonicolas** [comment]
Im struggling now to make that one work! having similar issues as before, don't know why they don't come complete. Now If I open APSP.xcodeproj it says Could not launch "APSP" failed to launch or debug process.

**Comment by vincentngo** [comment]
@magonicolas works for me, you just need to build both the APSP and Graph module. I did get the failed to launch debug process once, but the playground works.

**Comment by magonicolas** [comment]
Can`t make it work. Could you do a Quicktime screen capture of the process? Maybe im doing something wrong.

**Comment by magonicolas** [comment]
Definitely could make it work, But With this ShortestPath I could make What I need, If I could just print the path!

**Comment by vincentngo** [comment]
@magonicolas any luck with printing the path?

**Comment by magonicolas** [comment]
Yes! Thanks @vincentngo  for asking! I did it with shortest Path unweighted, and I also manage to make APSP work modifying the playground and adding all the needed swift files to it.

**Comment by vincentngo** [comment]
@magonicolas sounds good, have fun!
