### ISSUE TITLE
AVL tree improvements

### ISSUE THREAD

**Issue by hollance** [raywenderlich/swift-algorithm-club#36]
Some things that could be improved in the AVL tree:
- Explain how the rotations work.
- Unit tests. This is a fairly complex data structure so it would be good to have extensive tests.
- The code uses too much forced unwrapping.

**Comment by kelvinlauKL** [comment]
@hollance Adding this to a list at #317. Thanks Matthijs 👍

**Comment by kelvinlauKL** [comment]
Rotations explained via #319
