### ISSUE TITLE
[Request] Add spatial access trees

### ISSUE THREAD

**Issue by tkrajacic** [raywenderlich/swift-algorithm-club#363]
Would be great to see implementations for 

- ~Quad-trees [(https://en.wikipedia.org/wiki/Quadtree)](https://en.wikipedia.org/wiki/Quadtree)~
- R-trees [https://en.wikipedia.org/wiki/R-tree](https://en.wikipedia.org/wiki/R-tree)
- R*-trees [https://en.wikipedia.org/wiki/R*_tree](https://en.wikipedia.org/wiki/R*_tree)

Those are used to organize spatial data for very efficient and fast access and can be useful for doing MapKit related stuff even.

GameKit does have implementations for quite a few tree structures (e.g. [R-tree](https://developer.apple.com/reference/gameplaykit/gkrtree) , or [Quad-tree](https://developer.apple.com/reference/gameplaykit/gkquadtree)) already and has even some very nice diagrams available.

**Comment by kelvinlauKL** [comment]
Added, thanks for the suggestions!

**Comment by kelvinlauKL** [comment]
Reopening for Hacktoberfest contributions!

**Comment by JaapWijnen** [comment]
Aren't quad trees already implemented? So this applies to R, R*-trees right? Maybe an octree is also a nice addition.

**Comment by kelvinlauKL** [comment]
Updated, thanks @JaapWijnen

**Comment by JaapWijnen** [comment]
Added an octree with #635

**Comment by zhouhao27** [comment]
Is R-tree available now? Thanks.

**Comment by kelvinlauKL** [comment]
Doesn't seem like it! Closing this for now.
