### ISSUE TITLE
Solved Matrix

### ISSUE THREAD

**Issue by magonicolas** [raywenderlich/swift-algorithm-club#373]
Hello there! Im applying this algorithm for solving a problem with a lot of vertex and edges, and since the algorithm is 0(n^3) its very slow. I want to use the matrix already solved on my code, So, how Can I save the Matrix for just using it instead of calculating it each time?

**Comment by kelvinlauKL** [comment]
We'll need more information to understand your question.

What is the problem and what algorithm are you using?
