### ISSUE TITLE
Unexpected behavior in `wordsInSubtrie`

### ISSUE THREAD

**Issue by AdrianBinDC** [raywenderlich/swift-algorithm-club#378]
I was tinkering with this class and I tried to use the `wordsInSubtrie` method to return an array of strings. Here's what I did:

`var trie = Trie()`
`trie.insert(word: "test")`
`trie.insert(word: "another")`
`trie.insert(word: "exam")`
`print(trie.wordsInSubtrie(rootNode: trie.root, partialWord: "exam"))`

I would expect an array with just one element, exam, to be returned in the array. Instead, this array is what is returned:

`["examtest", "examanother", "examexam"]`

**Comment by kelvinlauKL** [comment]
Interesting! Will check that out.

**Comment by kelvinlauKL** [comment]
It seems like `wordsInSubtrie` isn't meant to be used publicly (i.e. it fails to work properly if you supply anything other than an empty string to `partialWord`).

This trie doesn't support prefix matching yet. Sounds like something to add to the Wishlist :). Thanks for the heads up!

**Comment by kelvinlauKL** [comment]
This is fixed!
