### ISSUE TITLE
Protocol ExpressibleByArrayLiteral question/suggestion

### ISSUE THREAD

**Issue by dsantosp12** [raywenderlich/swift-algorithm-club#396]
Do we want to satisfy the ExpressibleByArrayLiteral protocol for some of the linear data structure where it would make sense? That is LinkedList, Queue, Stack, etc. I've been looking to make a contribution and I think this will be suitable. Please let me know your opinions.

[Link to ExpressibleByArrayLiteral docs](https://developer.apple.com/reference/swift/expressiblebyarrayliteral)

**Comment by kelvinlauKL** [comment]
That sounds like a good idea. Will be happy to merge that in.

**Comment by dsantosp12** [comment]
I will start working on it.
