### ISSUE TITLE
Playground and code in swift differ in code

### ISSUE THREAD

**Issue by proyb6** [raywenderlich/swift-algorithm-club#406]
It was an eye opener to learn Swift algorithm, I've realized there were problem with code discrepancies in the repo between the `content.swift` in some playground folder and the swift file outside playground folder (is outdated for Swift 3). Is it a good idea to update and pull requests both playground and non-playground version? Let's keep all code up to date.

Old:
https://github.com/raywenderlich/swift-algorithm-club/blob/master/Ordered%20Array/OrderedArray.swift#L39

Updated:
https://github.com/raywenderlich/swift-algorithm-club/blob/master/Ordered%20Array/OrderedArray.playground/Contents.swift#L51

**Comment by kelvinlauKL** [comment]
Good catch. We finished up Swift 3 migration last month and that must have been missed. Feel free to open a PR and keep them both up to date.
