### ISSUE TITLE
Links in the Readme broken.

### ISSUE THREAD

**Issue by ybabenko** [raywenderlich/swift-algorithm-club#407]
Links in the Readme broken.

**Comment by dsantosp12** [comment]
In which readme?

**Comment by ybabenko** [comment]
![screen shot 2017-03-20 at 23 33 25](https://cloud.githubusercontent.com/assets/1170109/24120462/c00e6cb8-0dc5-11e7-8e05-9dcaed89ec62.png)
@dsantosp12 Many links are not clickable, Please check the screenshot.

**Comment by kelvinlauKL** [comment]
Noted. This isn't the first time - Github had hiccups last time. I'll look into this. Thanks!

**Comment by kyungkoo** [comment]
I send PR #411 please check.

**Comment by kelvinlauKL** [comment]
This is fixed. Thanks all!
