### ISSUE TITLE
Examples with Unsafe C and Swift

### ISSUE THREAD

**Issue by proyb6** [raywenderlich/swift-algorithm-club#410]
Would that be feasible to write `UnsafePointer` in the algorithm code?

One of the reasons was performance and it also give some good experience on learning how to write UnsafePointer code, until the Apple team is ready for Swift memory ownership model discussion and benchmarking purpose. This will be extremely useful to help Swift for uses as a system programming in the future.

**Comment by kelvinlauKL** [comment]
I think so. I haven't worked much with `UnsafePointer`, but I presume there are non negligible performance gains. 

It'll be interesting to see if using `UnsafePointer` can avoid the ARC.

**Comment by proyb6** [comment]
Unsure but I have seen a significant gain from this compare to pure Swift
https://benchmarksgame.alioth.debian.org/u64q/program.php?test=binarytrees&lang=swift&id=9
