### ISSUE TITLE
Could you please add Treap data structure?

### ISSUE THREAD

**Issue by kitgary** [raywenderlich/swift-algorithm-club#44]
It's very hard to find tutorials talking about [Treap](https://en.wikipedia.org/wiki/Treap), could you implement and teach it?

**Comment by hollance** [comment]
Sure. It's something I still have to study myself so it might take a little while. :-)

**Comment by goingreen** [comment]
The next structure I want to implement is actually treap. In my opinion, it's the most powerful data structure and it can solve many problems, so everyone should know it. Right now I'm a bit busy but I can implement it on the weekends.

**Comment by hollance** [comment]
Sounds good to me!

**Comment by rothomp3** [comment]
I have a pure-swift treap implementation, I'd be happy to dig it up and share it when I get back to my Mac.

**Comment by rothomp3** [comment]
Just as a note, if I don't have time to write up an explanation of how it works, etc (I don't), would you prefer I just attach it here instead of doing a pull request? I have a red-black tree implementation too.

**Comment by rothomp3** [comment]
I'm going to do the PR, but I don't really expect it to get merged as-is haha.

**Comment by hollance** [comment]
I'm happy to receive any code but I'd be even happier to also get an explanation. ;-) If you don't have time to write an explanation, then I'll take the code anyway. :-D

**Comment by chris-pilcher** [comment]
Thanks for PR #45 @rothomp3! 😄 I will close this issue since you've submitted a PR.
