### ISSUE TITLE
Bubble Sorting files are missing?

### ISSUE THREAD

**Issue by phynet** [raywenderlich/swift-algorithm-club#455]
### Category

- [x ] Bug
- [ ] Feature Request
- [ ] Question

### Brief Intro

Searching [Bubble Sorting](https://github.com/raywenderlich/swift-algorithm-club/tree/master/Bubble%20Sort) only shows a README file without any code, playground code, etc. I'm looking in the wrong area?

<img width="1025" alt="screen shot 2017-05-03 at 12 28 53" src="https://cloud.githubusercontent.com/assets/724536/25657038/1df2d302-2ffc-11e7-8036-ca4546606970.png">

### More Details

¯\_(ツ)_/¯

**Comment by kelvinlauKL** [comment]
It used to be our [joke page](https://github.com/raywenderlich/swift-algorithm-club/commit/e47743d54bf4afea0fc0f28d897c77b2679d993d).

Someone decided to update it with a glimpse of what it's about instead.

**Comment by phynet** [comment]
XD 

so this applies -> ¯\_(ツ)_/¯

I needed to ask anyway! Thanks

**Comment by kelvinlauKL** [comment]
One day...
