### ISSUE TITLE
Wrong result for multiplication 

### ISSUE THREAD

**Issue by belkhadir** [raywenderlich/swift-algorithm-club#458]
### Category

- [x] Bug
- [ ] Feature Request
- [ ] Question

### Brief Intro

When i try to multiply jordanMatrix * M * transposeOfJordanMatrix 
i got wrong multiplication  
### More Details

i added this  properties and init
```
  public var transpose: Matrix<T> {
        var result = Matrix(rows: columns, columns: rows)
        for i in 0..<rows {
            for j in 0..<columns {
                result[j,i] = self[i,j]
            }
        }
        return result
    }
    
    public var jordan: Matrix<T> {
        var jordan = Matrix<T>(rows: rows, columns: columns)
        for i in 0..<rows-1 {
            jordan[i+1,i] = T.one
        }
        return jordan
    }

  public init(rows: Int, columns: Int, grid: [T]) {
        self.rows = rows
        self.columns = columns
        self.size = Size(rows: rows, columns: columns)
        self.grid = grid
    }
```
I'm trying to calulate 
```
let convert: [Int] = [255,255,0,0,
                       255,255,0,0,
                        0,0,0,0,
                        0,0,0,0]
let matrix = Matrix<Int>(rows: 4, columns: 4, grid: convert)
let jordan = Matrix<Int>(rows: 4, columns: 4).jordan
let transposeJordan = jordan.transpose
let center = (jordan * matrix) * transposeJordan
```
The result should be [0,   0,     0,    0,
                                     0, 255, 255 , 0,
                                     0, 255, 255 , 0,
                                     0.      0,     0 , 0]

But i got                        [0,0, 0, 0,
                                     0, 0, 0 , 0,
                                     0, 0, 0 , 0,
                                     0,  0,  0 , 0]

**Comment by kelvinlauKL** [comment]
Which data structure/algorithm is this based on?

**Comment by belkhadir** [comment]
it's based on yours just adding simple classical matrix

**Comment by kelvinlauKL** [comment]
Could you tell me the title of the directory in this repository?

**Comment by belkhadir** [comment]
public var jordan: Matrix<T> {
        
        var jordan = Matrix<T>(rows: rows, columns: columns)
        for i in 0..<rows-1 {
            jordan[i+1,i] = T.one
        }
        return jordan
    }
public func transposed() -> Matrix<T> {
        let newElements = Matrix<T>(rows: rows, columns: columns)
        for r in 0..<rows {
            for c in 0..<columns {
                newElements[c*rows+r] = grid[r*columns+c]
            }
        }
        return Matrix(rows: columns,
                      columns: rows,
                      initialValue: newElements)
    }
I add just this two method

**Comment by kelvinlauKL** [comment]
I apologize for the late reply on this issue. Since this issue is a couple months old, I'm closing this issue. 

If this still concerns you, please feel free to reopen the issue and I'll make sure to follow up with it. Thanks!
