### ISSUE TITLE
Threaded Binary Tree

### ISSUE THREAD

**Issue by daisysomus** [raywenderlich/swift-algorithm-club#464]
### Category

- [x] Bug
- [ ] Feature Request
- [ ] Question

### Brief Intro

Deletion logic is unperfect in the example of deleting node **7**.  we should set **7**'s parent's right child to nil.

### More Details
The original text doesn't mentioned the above logic.

```
Before we can just throw **7** away, we have to perform some clean-up.  In this
case, because **7** is a `right` child and has no children itself, we can
simply set the `rightThread` of **7**'s `parent`(**5**) to **7**'s (now
outdated) `rightThread`.  Then we can just set **7**'s `parent`, `left`,
`right`, `leftThread`, and `rightThread` to `nil`, effectively removing it from
the tree.
```

**Comment by kelvinlauKL** [comment]
Looking into this.

**Comment by kelvinlauKL** [comment]
Yep, you're right. 

In the implementation, there is code to set the parent's right child to `nil` via the `reconnectParentToNode` method. The readme doesn't reference that. I'll make changes, thanks!
