### ISSUE TITLE
Algorithm Problems

### ISSUE THREAD

**Issue by imrvshah** [raywenderlich/swift-algorithm-club#470]
### Category

- [ ] Bug
- [ ] Feature Request
- [x] Question

### Brief Intro

This is the repository I was looking for since long time as I am learning algorithms and solving problems. I was solving a problem before in JAVA and now I started to use swift so this repo is so much useful. Thank you so much for putting all in one place. 

I used to solve many problems online through different websites. I am a beginner for swift 3 and sometimes it's difficult to find a solution for certain problems pure in swift 3.0 (relatively new language) so, do you guys have any plan to put the problems which are related to algorithm into the current repository? Or it is solely for data structures and known algorithms?

**Comment by kelvinlauKL** [comment]
We welcome contributions in the form of technical questions as well. It's just that so far, most of the contributions have been on specific data structures and algorithms.

**Comment by imrvshah** [comment]
Thank you for your reply. 
I am looking forward to contribute whenever I get something to put in.
