### ISSUE TITLE
https://github.com/raywenderlich/swift-algorithm-club/tree/master/Selection%20Sampling#selection-sampling

### ISSUE THREAD

**Issue by WarMap** [raywenderlich/swift-algorithm-club#475]
in [Selection Sampling](https://github.com/raywenderlich/swift-algorithm-club/tree/master/Selection%20Sampling#selection-sampling)

![59c4a8e8-4e8f-4e2a-8ff1-6722e96221e7](https://cloud.githubusercontent.com/assets/16216348/26290054/4a6df9c2-3ed7-11e7-8dab-afd0ea6c458d.png)

why not write like below

<img width="604" alt="cbb429ec-125e-465a-8bf0-1135fea09c91" src="https://cloud.githubusercontent.com/assets/16216348/26290110/9f089a82-3ed7-11e7-9c28-d09068571544.png">

**Comment by kelvinlauKL** [comment]
Yep that makes sense! I'll add this as a TO-DO item.

**Comment by kelvinlauKL** [comment]
Fixed in #631
