### ISSUE TITLE
Missing projects

### ISSUE THREAD

**Issue by ph1ps** [raywenderlich/swift-algorithm-club#477]
### Category

- [ ] Bug
- [ ] Feature Request
- [x] Question

### Brief Intro

Some of the projects are not listed in the README.md

### More Details

I've noticed that some of the projects are not listed in the README.md. Also the reason why I didn't simply open a PR for this is that I need a short description for all of those and this would take quite some time reading through all of them. Maybe I will start or someone could help (like the developers themselves).
Correct this issue if I was blind and they are there. Thanks!

Here is a list:

Convex Hull
Miller-Rabin Primality
Minimum Coin Change
Quad Tree

**Comment by kelvinlauKL** [comment]
Thanks for the note. I'll add them in.
