### ISSUE TITLE
I would like to translate this document so that Korean developers can see and study it.

### ISSUE THREAD

**Issue by SH4CK3RS** [raywenderlich/swift-algorithm-club#480]
### Category

- [ ] Bug
- [ ] Feature Request
- [ v ] Question

### Brief Intro

Hello I am a student studying Swift in Korea. 
First, I would like to thank you for providing this excellent documents.
When I was studying, I thought that Koreans who are not familiar with English would feel a lot of difficulties.
So I would like to translate this document into Korean a little bit a day, so that many Korean developers can easily see it.
If it does not matter, and if you do not mind, I would like to do the above. What do you think?
If you do not mind, please reply by email or leave me a comment.
My email is qudrms007@naver.com.
Thank you.

**Comment by kelvinlauKL** [comment]
Hey @SH4CK3RS 

We don't mind at all. In fact, I would encourage you to do it. There's a lot of information here and I'd like nothing more if more people can benefit from it. 

Our current guidelines for translations is that you fork the repo and handle the translations in the fork. We'll add a link in our `README` to your fork to direct anyone who wants to read the Korean translation. 

Thanks for asking!
