### ISSUE TITLE
Tests For Minimum Spanning Trees

### ISSUE THREAD

**Issue by pwentz** [raywenderlich/swift-algorithm-club#485]
### Category

- [ ] Bug
- [ ] Feature Request
- [ ] Question
- [x] Improvement

### Brief Intro

I've found the [Minimum Spanning Trees](https://github.com/raywenderlich/swift-algorithm-club/tree/master/Minimum%20Spanning%20Tree) repo difficult to learn from due to a lack of tests. Also hard to step through the code when solutions are employing a 200+ line data structure.

### More Details

Permission to add some unit tests and simplify some of these data structures to improve the approachability of this repo?

**Comment by kelvinlauKL** [comment]
Improvements and suggestions are always appreciated :)

**Comment by pwentz** [comment]
@kelvinlauKL Is there any instructions on the xcode aspect of how to contribute? The existing Contribution README has not helped me much. Why are there so many different schemes named `Tests`? Should I create a new scheme every time I need to contribute? If so, what should I select as the Target when I'm trying to add unit tests to existing files?

Thanks

**Comment by pwentz** [comment]
If someone would be willing to walk me through the process via ScreenHero, I'd be happy to document the experience and include in a PR so future contributors can have an easier time making improvements.

**Comment by kelvinlauKL** [comment]
@pwentz Sorry for late reply. I believe the main `xcworkspace` is auto generated, so it's been listing all the schemes from each individual contribution with a build target. 

I believe @chris-pilcher set this up in the past. @chris-pilcher could you shed some light into how this works?

Anyhow, I think adding a new test project inside the Minimum Spanning Trees folder will work for me.

**Comment by pwentz** [comment]
> Anyhow, I think adding a new test project inside the Minimum Spanning Trees folder will work for me.

This is all I'm really trying to do. All of the other repos have a `Tests.xcodeproj` file in their Tests directory, and I'd like to follow that trend. However I've only ever worked with SPM and therefore don't know the process of safely adding a test target to an xcode repo. Any help would be greatly appreciated !

**Comment by kelvinlauKL** [comment]
We've got a great tutorial on unit tests: https://www.raywenderlich.com/150073/ios-unit-testing-and-ui-testing-tutorial
