### ISSUE TITLE
convex hull implementation sometimes produces incorrect result

### ISSUE THREAD

**Issue by treinberger** [raywenderlich/swift-algorithm-club#487]
### Category

[ x] Bug
[ ] Feature Request
[ ] Question

### Brief Intro

Und some circumstances, the convex hull implementation provides wrong results.

### More Details

Reproduction:

1. open the convex hull project in xCode.
2. In View.swift replace the function generatePoints() with the following code:

```
    func generatePoints() {
        
        // [(22.0, 22.0), (157.0, 447.0), (146.5, 284.0), (353.0, 22.0)]
        points.append(CGPoint(x: 22, y: 22))
        points.append(CGPoint(x: 157, y: 447))
        points.append(CGPoint(x: 146, y: 284))
        points.append(CGPoint(x: 353, y: 22))

        points.sort { (a: CGPoint, b: CGPoint) -> Bool in
            return a.x < b.x
        }
    }
```

3. Start the app. The shape shown is concave because the inner angle at one of the four points is greater than 180 degrees.

**Comment by kelvinlauKL** [comment]
Fixed by #630
