### ISSUE TITLE
How generic the question should be?

### ISSUE THREAD

**Issue by remlostime** [raywenderlich/swift-algorithm-club#491]
### Category

- [ ] Bug
- [ ] Feature Request
- [x] Question

### Brief Intro

I found some algorithms are pretty specific. Like [find occurrence](https://github.com/raywenderlich/swift-algorithm-club/tree/master/Count%20Occurrences). So I am wondering how generic the algorithm should be here?

### More Details

There is an algorithm website [leetcode](https://leetcode.com/problemset/algorithms/). There are tons of questions there. If the find occurrence could be accepted here. I think I can move most answers there to here. Thoughts?

**Comment by kelvinlauKL** [comment]
We'd welcome specific questions, (for example: interview type questions).
