### ISSUE TITLE
Swift 4 Migration 

### ISSUE THREAD

**Issue by kelvinlauKL** [raywenderlich/swift-algorithm-club#507]
# Update

Thanks everyone for helping out with the migration! Another year, another migration complete :]
___

It's that time of the year again. Swift 4 is imminent, so it's time to begin migration. Swift 3 to Swift 4 has been relatively painless compared to other years, so things should go rather smoothly!

## Migration Procedure:

1. Choose a topic below that hasn't been checked off
2. Check the pull requests to see if anyone is working on your chosen topic
3. Make a pull request to let others know that you're currently working on your chosen topic
4. 

* Add the following code snippet at the top of each playground file:

```
// last checked with Xcode 9.0b4
#if swift(>=4.0)
   print("Hello, Swift 4!")
#endif
```

* Make sure the code for the topic compiles correctly with the latest Xcode 9 beta (currently beta 4). 
* Make sure that the README.md file reflects the updated playground

## Current Progress

- [x] AVL Tree
- [x] All-Pairs Shortest Paths
- [x] Array2D
- [x] B-Tree
- [x] Binary Search Tree
- [x] Binary Search
- [x] Binary Tree
- [x] Bit Set
- [x] Bloom Filter
- [x] Bounded Priority Queue
- [x] Boyer-Moore
- [x] Breadth-First Search
- [x] Brute-Force String Search
- [x] Bubble Sort
- [x] Bucket Sort
- [x] Comb Sort
- [x] Combinatorics
- [x] Convex Hull
- [x] Count Occurrences
- [x] Counting Sort
- [x] Depth-First Search
- [x] Deque
- [x] Dijkstra Algorithm
- [x] DiningPhilosophers
- [x] Fixed Size Array
- [x] Fizz Buzz
- [x] GCD
- [x] Graph
- [x] Hash Set
- [x] Hash Table
- [x] HaversineDistance
- [x] Heap Sort
- [x] Heap
- [x] Huffman Coding
- [x] Insertion Sort
- [x] K-Means
- [x] Karatsuba Multiplication
- [x] Knuth-Morris-Pratt
- [x] Kth Largest Element
- [x] LRU Cache
- [x] Linear Regression
- [x] Linear Search
- [x] Linked List
- [x] Longest Common Subsequence
- [x] Merge Sort
- [x] Miller-Rabin Primality Test
- [x] Minimum Edit Distance
- [x] Minimum Spanning Tree (Unweighted)
- [x] Minimum Spanning Tree
- [x] MinimumCoinChange
- [x] Monty Hall Problem
- [x] Ordered Array
- [x] Ordered Set
- [x] Palindromes
- [x] Priority Queue
- [x] QuadTree
- [x] Queue
- [x] Quicksort
- [x] Rabin-Karp
- [x] Radix Sort
- [x] Radix Tree
- [x] Red-Black Tree
- [x] Ring Buffer
- [x] Rootish Array Stack
- [x] Run-Length Encoding
- [x] Segment Tree
- [x] Select Minimum Maximum
- [x] Selection Sampling
- [x] Selection Sort
- [x] Set Cover (Unweighted)
- [x] Shell Sort
- [x] Shortest Path (Unweighted)
- [x] Shuffle
- [x] Shunting Yard
- [x] Single-source Shortest Paths(Weighted)
- [x] Skip-List
- [x] Slow Sort
- [x] Stack
- [x] Strassen Matrix Multiplication
- [x] Ternary Search Tree
- [x] Threaded Binary Tree
- [x] Topological Sort
- [x] Treap
- [x] Tree
- [x] Trie
- [x] Two-Sum Problem
- [x] Union-Find
- [x] Z-Algorithm

**Comment by shabirjan** [comment]
Hi i want to contribute in this task.

**Comment by kelvinlauKL** [comment]
@shabirjan Cool. I've updated the issue to include the steps you'd want to do.

**Comment by bobdel** [comment]
There are no pull requests as of yet "claiming" items, correct? I was looking for an example of how to do one.

Also, I suggest adding the following code to each of the playgrounds: Either that, or just the comment either in the code or the readme so its instantly obvious which items are up to date from inside the playground.
```
// last checked with Xcode 9.0b4
#if swift(>=4.0)
print("Hello, Swift 4!")
#endif

```

**Comment by kelvinlauKL** [comment]
@bobdel That's actually a good idea!

**Comment by coolbnjmn** [comment]
I've claimed 2Sum with this PR: https://github.com/raywenderlich/swift-algorithm-club/pull/513

@kelvinlauKL lmk if I need to fix up anything in that until it's ready (should be quite shortly, just didn't want any duplication of effort :D ).

**Comment by coolbnjmn** [comment]
@kelvinlauKL PR #513 is ready to go, I didn't put the `#ifdef` but I used it to just sanity check. I added the comment with the exact build number I used (beta4) to check. If this is all that's needed, I'll attack another soon but this one needed no changes. PR only added the comment that it was checked in Xcode9b4. Not sure if I'm missing something though, lmk!

**Comment by shabirjan** [comment]
@kelvinlauKL  PR [#516](https://github.com/raywenderlich/swift-algorithm-club/pull/516) claimed Bucketsort and is ready to go :)

**Comment by remlostime** [comment]
Bubble sort has no implementation. We are good to mark it as done.

**Comment by shabirjan** [comment]
#545 AVL tree is updated for Swift 4.

**Comment by remlostime** [comment]
@shabirjan I already updated the DFS.

**Comment by KelCodesStuff** [comment]
I would like to work on the Binary Search Tree but I am unable to make a PR.

**Comment by remlostime** [comment]
@KelCodesStuff Actually I already sent the binary search tree diff.

**Comment by danielStokowski** [comment]
#580

**Comment by vuinguyen** [comment]
Hi @kelvinlauKL ! I'm new to the Swift Algorithm Club, but would love to help! Are there any left that I can help update to Swift 4? Also, I'm a bit rusty since I haven't done algorithms since my CS grad school days (although I'm sure I can pick it again :) ). Let me know what you think!

**Comment by remlostime** [comment]
@vuinguyen Check all PRs in the comment, make sure you don't repeat work. I believe you can work on QuadTree. It seems that no one works on it. Actually convert to swift 4 does not need too much algorithm background. Just make sure the syntax is correct. Download Xcode 9 and then run the algorithm. That's it. Also, feel free to pick some simple algorithms to read first to ramp up like bubble sort, string compare.

**Comment by vuinguyen** [comment]
@remlostime Thanks for your advice! I will work on QuadTree then, if no one else is doing it.

**Comment by shabirjan** [comment]
@remlostime is there any algorithm left for Swift 4 Conversion?

**Comment by remlostime** [comment]
@shabirjan Only few left. You can check the PR I pasted here and pick the one doesn't exist.

**Comment by kelvinlauKL** [comment]
@shabirjan made quite a few merges just now. The list should better reflect what's left. Thanks for the efforts guys!

**Comment by remlostime** [comment]
GCD has been updated already.

**Comment by remlostime** [comment]
Segment Tree has been updated already.

**Comment by remlostime** [comment]
@kelvinlauKL I didn't see Dijkstra algorithm in the codebase. Could you point out where it is?

**Comment by kelvinlauKL** [comment]
We're done... just in time for Swift 4! Thanks everyone!

**Comment by remlostime** [comment]
Awesome! Time to party! :)

**Comment by rwenderlich** [comment]
Congratulations everyone - this community rules! 🎉
