### ISSUE TITLE
Please add some graph layout algorithms from the Open Graph Drawing Framework (OGDF)

### ISSUE THREAD

**Issue by Emasoft** [raywenderlich/swift-algorithm-club#59]
An important field of algorithm missing from the examples implementations in Swift is the field of graph algorithms. You can find many algorithms in the Open Graph Drawing Framework (OGDF). It is a popular open source C++ library of algorithms and data structures for graph drawing.

http://cs.brown.edu/~rt/gdhandbook/chapters/ogdf.pdf

http://www.ogdf.net

Please add some graph algorithm examples in the Swift algorithm club, thank you!

**Comment by hollance** [comment]
This repo is still quite young and we just haven't gotten to the graphs yet (although some stuff is in the works). 

Thanks for the link to OGDF, that looks very useful!
