### ISSUE TITLE
Dijkstra running time

### ISSUE THREAD

**Issue by jmoyers** [raywenderlich/swift-algorithm-club#614]
### Category

- [ ] Bug
- [ ] Feature Request
- [x] Question

### Brief Intro

Heya,

Just wanted to point out that current Dijkstra implementation is O(n^2) (I believe). It has a good explanation and visualization of the core concept, but is lacking the data structure to make it the more modern E log V running time.

1) The vertex storage is a Set (which are unordered, but unique in Swift)

https://github.com/raywenderlich/swift-algorithm-club/blob/master/Dijkstra%20Algorithm/Dijkstra.playground/Sources/Dijkstra.swift#L4

2) The next vertex to examine for edge relaxation is chosen based on a min operation on the Set

https://github.com/raywenderlich/swift-algorithm-club/blob/master/Dijkstra%20Algorithm/Dijkstra.playground/Sources/Dijkstra.swift#L38

I believe this operation dominates the running time. Because Set is unordered, it means the running time upper bound is O(n^2). 

I believe modern implementations use some kind of priority queue for vertexes, where the distance to the source vertex is the key. A minimum heap (which you guys have a great implementation of [in the repository](https://github.com/raywenderlich/swift-algorithm-club/blob/master/Heap/Heap.swift)!) that allows you to decrease the key after insertion makes this algorithm run in linearithmic time (E log V, where E is the number of edges and V the number of vertexes).

Edit: I should also point out that if you have a very dense/small graph, the array/set implementation can be faster. However, in practice, sparse/large graphs are common when in need of a fast shortest path algorithm.

**Comment by kelvinlauKL** [comment]
Thanks for making a note of this. I'll write that into #316 for contributors to be aware of.

Cheers!

**Comment by kelvinlauKL** [comment]
Reopened for Hacktoberfest contributions!

**Comment by aleph7** [comment]
The data structure to use for this is the HashedHeap, see the [implementation of A*](https://github.com/raywenderlich/swift-algorithm-club/pull/633)
