### ISSUE TITLE
PR review speed

### ISSUE THREAD

**Issue by remlostime** [raywenderlich/swift-algorithm-club#622]
### Category

- [ ] Bug
- [ ] Feature Request
- [x] Question

### Brief Intro

Idea about solving the speed of reviewing PR

### More Details

It seems that currently reviewing PR speed is kind of slow. Want to create this issue to get some feedback about the speed of reviewing PR.

**Comment by remlostime** [comment]
Here are some ideas how to solve it.
* Add more reviewers
* Get a plan for each week or each month. How many PRs need to be reviewed. We can rank the importance of PRs. Like fatal bug, new features, small issues, PR waiting time etc. Based on the rank to clean up PRs in the queue.

@kelvinlauKL @rwenderlich @vincentngo

**Comment by kelvinlauKL** [comment]
@remlostime Thanks for bringing this up, you've brought up good points. 

As the repo gets more popular, we'll be adding more reviewers. Traffic certainly has picked up lately. We generally plan for a couple of PRs per week per reviewer, but the Swift 4 migration created a backlog of things for us to take a look at. 

I do acknowledge the need for a more speedy resolution to resolve the bucket of PRs though. Thanks again for the feedback, it's appreciated.

**Comment by remlostime** [comment]
@kelvinlauKL Thanks for the reply. That helps.
