### ISSUE TITLE
Cache LRU implementation

### ISSUE THREAD

**Issue by MarcoSantarossa** [raywenderlich/swift-algorithm-club#627]
### Category

- [ ] Bug
- [x] Feature Request
- [ ] Question

### Brief Intro

Hi there! I've recently implemented a Cache LRU with Swift. I had a look at your implementation and I see that you guys are using two dictionaries and a linked list. I would suggest a version with only a dictionary and a doubly linked list. It would save space complexity. Moreover, this version is suggested in several tutorials.
I know, it's not a big deal but it would safe space complexity which may be worth it. If you like this version, I wouldn't mind creating a PR with that.

### More Details

You can find a Gist of my implementation here:

https://gist.github.com/MarcoSantarossa/e21599d028a9187e4f88e767f8d2acf0

**Comment by kelvinlauKL** [comment]
Hi Marco, 

Great suggestion. I approve :]

**Comment by MarcoSantarossa** [comment]
Perfect, thank you! I'll work on it asap!
