### ISSUE TITLE
Improve Big O explanations

### ISSUE THREAD

**Issue by kelvinlauKL** [raywenderlich/swift-algorithm-club#632]
### Brief Intro

Add examples for Big O notation 

### More Details

Our article [here](https://github.com/raywenderlich/swift-algorithm-club/blob/master/Big-O%20Notation.markdown) is a brief guide on Big O notation. It would be helpful for beginners if we added snippets of code as an example for each case.

**Comment by nb2998** [comment]
I would like to work on this.

**Comment by kelvinlauKL** [comment]
@nb2998 Thanks for volunteering! If you need any help, leave a note in this issue to let others know. Otherwise, make sure you create a PR right away to let others know that you're working on it.

Looking forward to it!

**Comment by nb2998** [comment]
Thanks! I wanted to know if the code snippets for each case should be provided in the table itself or after the table?

**Comment by kelvinlauKL** [comment]
The table looks packed already, so I would put it after the table. Perhaps even in a new section. The table serves as a quick reference for those that just need a refresher. 

We could iron down the finer details of the layout once we got a draft going. Thanks again for picking this up!
