### ISSUE TITLE
can't search 55

### ISSUE THREAD

**Issue by fanglichun** [raywenderlich/swift-algorithm-club#639]
### Brief Intro
let testArray = [1, 2, 3, 65, 55, 100]
binarySearch(testArray, key: 55) 
I always get nil
And I must sort the testArray then I always get correct result.
When in  big data scene, do I must sort the array and query the value? I think it is not a good idea.

**Comment by kelvinlauKL** [comment]
Hey @fanglichun, just to make sure, are you referring to the code for [binary search](https://github.com/raywenderlich/swift-algorithm-club/blob/master/Binary%20Search/BinarySearch.playground/Contents.swift)?

**Comment by kelvinlauKL** [comment]
It makes sense to me that you get `nil`. 

**Binary Search** by definition *only* works on pre-sorted data. If your data is not sorted, you would not use binary search to do it. 

Linear Search is `O(n)` in sorted/unsorted data.

Binary Search is `O(log n)` in sorted data, but doesn't work at all for unsorted data.

**Comment by fanglichun** [comment]
I got it, thank you very much.
