### ISSUE TITLE
Github Page?

### ISSUE THREAD

**Issue by aquarchitect** [raywenderlich/swift-algorithm-club#640]
### Brief Intro

This [GitHub Page](https://aquarchitect.github.io/swift-algorithm-club/) is my second attempt to create something easier to read all of these wonderful algorithm articles. 

### More Details

I wrote a [bash script](https://github.com/aquarchitect/swift-algorithm-club/blob/gh-pages/gfm-render.sh) to generate HTML automatically, which ultimately can be integrated into Travis CI. 

My goal was to create an ePub, but both of my experiments with Pandoc and Calibre were unsuccessful. I think a webpage is still good enough to read on a mobile device. 

If you are interested, I can make a PR.

**Comment by kelvinlauKL** [comment]
Sounds like a great addition. What kind of maintenance effort would be required to have this feature?

**Comment by aquarchitect** [comment]
@kelvinlauKL It would be very little to none. The idea is to get it working and hopefully you can forget about it.

The feature involves the following files:
- [gfm-render.sh](https://github.com/aquarchitect/swift-algorithm-club/blob/gh-pages/gfm-render.sh) to render Markdown into HTML.
- .travis.yml with a modification to execute the script above.

I hope my answer addresses your concerns.

**Comment by kelvinlauKL** [comment]
Sounds good. Looking forward to the PR!

**Comment by aquarchitect** [comment]
For further discussion on the topic, please refer to #647.
