### ISSUE TITLE
Dijkstra's Algorithm vs A*

### ISSUE THREAD

**Issue by KelCodesStuff** [raywenderlich/swift-algorithm-club#641]
### Should developers forget about Dijkstra's Algorithm?

Should Dijkstra's Algorithm be replaced with A* in the Swift Algorithm Club and forgotten in general since A* is a faster variation?

Or do you think Dijkstra's Algorithm is good when first learning about pathfinding?

Also from what I've seen, A* will default to Dijkstra's Algorithm based on the heuristic function used? Is this correct?

**Comment by kelvinlauKL** [comment]
Good question!

I think Dijkstra's should stay. A* isn't taught in introductory algorithm courses (in my school).

**Comment by JaapWijnen** [comment]
I say let it stay but do reference A* in the readme as a faster variation.

**Comment by JaapWijnen** [comment]
@kelvinlauKL I think we can close this do you agree?

**Comment by kelvinlauKL** [comment]
@JaapWijnen Yep.
