### ISSUE TITLE
how to run APSP ?

### ISSUE THREAD

**Issue by badapple47** [raywenderlich/swift-algorithm-club#642]
### Brief Intro
I try to run  APSP with APSP.xcworkspace  and APSP.playground but both not working seem it missing such module 'Graph' or I did something wrong?

<img width="1252" alt="screenshot 2017-10-18 17 58 51" src="https://user-images.githubusercontent.com/21506010/31716350-9377a076-b431-11e7-8893-dddc5684c0f7.png">

**Comment by kelvinlauKL** [comment]
I opened the workspace and built it. Runs for me.

**Comment by JaapWijnen** [comment]
That's the point. You should open the workspace and not just the playground @badapple47

**Comment by badapple47** [comment]
@kelvinlauKL @JaapWijnen  Thank for the answer.  but how can I migrate .framework (which get from DerivedData) to my ios project  

I try import APSP.framework & Graph.framework to my project but this error appear 
"Module file was created for incompatible target x86_64-apple-macosx10.11: /Users/st4rboy/Desktop/testframework/testframework/APSP.framework/Modules/APSP.swiftmodule/x86_64.swiftmod"

**Comment by kelvinlauKL** [comment]
It looks like you're trying to import the framework into an iOS project. 

Your error just means you're trying to target an architecture other than x86_64, which is for mac apps. 

I presume you want to target iOS, which operates on arm_64. You'd have to use something like libtool to convert it into one. 

I _think_ Carthage can also help you out with this. Please note that this repo isn't built for development use, but as a learning resource. I don't know how the framework will work with your project. I suggest copying the code directly into the project if you wanted to use a specific data structure or algorithm.
