### ISSUE TITLE
SplayTree.remove is broken

### ISSUE THREAD

**Issue by roselma** [raywenderlich/swift-algorithm-club#659]
In this example, remove never returns.

        var tree = SplayTree<Int>()
        tree.insert(value: 0)
        tree.insert(value: 2)
        tree.insert(value: 3)
        tree.insert(value: 4)
        tree.insert(value: 7)
        _ = tree.search(value: 2)
        tree.remove(value: 2)

In this example, the value 4 disappears from the tree after 0 and 2 are removed.

        var tree = SplayTree<Int>()
        tree.insert(value: 0)
        tree.insert(value: 1)
        tree.insert(value: 2)
        tree.insert(value: 3)
        tree.insert(value: 4)
        tree.insert(value: 7)
        _ = tree.search(value: 0)
        tree.remove(value: 0)
        _ = tree.search(value: 0)
        _ = tree.search(value: 2)
        tree.remove(value: 2)

**Comment by kelvinlauKL** [comment]
Verified to be a bug. Thanks for letting us know!

**Comment by richard-ash** [comment]
Merged 👍
