### ISSUE TITLE
Binary Search , The index value cannot be obtained 

### ISSUE THREAD

**Issue by shyh5** [raywenderlich/swift-algorithm-club#667]
### More Details
'''
func binarySearch<T: Comparable>(_ a: [T], key: T, range: Range<Int>) -> Int? {
    if range.lowerBound >= range.upperBound {
        // If we get here, then the search key is not present in the array.
        return nil

    } else {
        // Calculate where to split the array.
        let midIndex = range.lowerBound + (range.upperBound - range.lowerBound) / 2

        // Is the search key in the left half?
        if a[midIndex] > key {
            return binarySearch(a, key: key, range: range.lowerBound ..< midIndex)

        // Is the search key in the right half?
        } else if a[midIndex] < key {
            return binarySearch(a, key: key, range: midIndex + 1 ..< range.upperBound)

        // If we get here, then we've found the search key!
        } else {
            return midIndex
        }
    }
}
'''
if create  an array = [2, 3, 5, 555, 111, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59, 61, 5566]
i use this func to get index . but the index value of 555 and 111 cannot be obtained. 
It is not the three digits that get the index。。

**Comment by hollance** [comment]
Binary search only works on sorted arrays. Your array is not sorted.

**Comment by shyh5** [comment]
o。o thank you！！！！I didn't notice that.....☺  I am a rookie，thank you  very much

**Comment by kelvinlauKL** [comment]
Closed as resolved!
