### ISSUE TITLE
QuickSort pre shuffle array

### ISSUE THREAD

**Issue by n0an** [raywenderlich/swift-algorithm-club#668]
### Brief Intro

Maybe it's worth to mention in QuickSort article, that you should shuffle input array before sorting it by QuickSort algorithm.

### More Details
QuickSort best practice is to always shuffle input array before sorting, to get right performance O(n log n).
Because If input array is already sorted, or almost sorted, QuickSort performance will be quadratic - O(n2).

**Comment by hollance** [comment]
Doesn't that depend on how you choose the pivot element, i.e. choosing the pivot randomly achieves the same thing as shuffling the array first.

**Comment by n0an** [comment]
Yes, with random pivot, performance is O(n log n). And actually there's mention about already sorted array:
"Because of the choice of pivot, this performs badly if the array is already sorted"
I'm closing issue 👍
