### ISSUE TITLE
Some thoughts on the implementation of AVL Tree's height

### ISSUE THREAD

**Issue by ShannonChenCHN** [raywenderlich/swift-algorithm-club#669]
### Issue Detail

When I tested the [AVL Tree](https://github.com/raywenderlich/swift-algorithm-club/blob/master/AVL%20Tree/AVLTree.swift) class like the code below:

``` Swift
let tree = AVLTree<Int, String>()
tree.insert(key: 5, payload: "five")
tree.insert(key: 4, payload: "four")
tree.insert(key: 3, payload: "three")
tree.insert(key: 2, payload: "two")
tree.insert(key: 1, payload: "one")
print(tree)
```

So I got a tree like this(so the height of this tree is 2):
``` Swift
                           4
                          /  \
                        2     5
                       /  \   
                     1    3
```

But the console output says the height of the root node(key is 4) is 3, according to our implementation:
``` Swift
5
(4) <- 5
(3) <- 4 -> (5)
((2) <- 3) <- 4 -> (5)
((1) <- 2 -> (3)) <- 4 -> (5)
key: 4, payload: Optional("four"), height: 3, left = [key: 2, payload: Optional("two"), height: 2, parent: 4, left = [key: 1, payload: Optional("one"), height: 1, parent: 2], right = [key: 3, payload: Optional("three"), height: 1, parent: 2]], right = [key: 5, payload: Optional("five"), height: 1, parent: 4]
```

It seems like the height calculation for an AVL Tree in [this implementation](https://github.com/raywenderlich/swift-algorithm-club/blob/master/AVL%20Tree/AVLTree.swift) does  not follow [the definition of the height of a basic binary tree](https://github.com/raywenderlich/swift-algorithm-club/tree/master/Tree). 

In our [tutorial for basic tree](https://github.com/raywenderlich/swift-algorithm-club/tree/master/Tree), it says as following: 
> **Height of the tree**. This is the number of links between the root node and the lowest leaf. In our example the height of the tree is 3 because it takes three jumps to go from the root to the bottom.

And it doesn't correspond to the [diagram](https://github.com/raywenderlich/swift-algorithm-club/blob/master/AVL%20Tree/Images/BalanceNotOK.png) in the tutorial either.

This is the diagram used in our tutorial for AVL Tree:
![](https://github.com/raywenderlich/swift-algorithm-club/blob/master/AVL%20Tree/Images/BalanceNotOK.png?raw=true)

### My Solution

According to the definition of the height of an basic tree, as shown above, the height of a leaf is 0. 
So I made a small change to the [method `updateHeightUpwards` implementation](https://github.com/raywenderlich/swift-algorithm-club/blob/master/AVL%20Tree/AVLTree.swift#L170).

``` Swift
fileprivate func updateHeightUpwards(node: Node?) {
        if let node = node {
            let lHeight = node.leftChild?.height ?? 0
            let rHeight = node.rightChild?.height ?? 0
            
            // node.height = max(lHeight, rHeight) + 1  // original implementation
            node.height = max(lHeight, rHeight) + (node.hasAnyChild ? 1 : 0)  // If we don't have any child, why do we need to add 1 ???
            
            updateHeightUpwards(node: node.parent)
        }
    }
```

**Comment by kelvinlauKL** [comment]
Good catch.

The current implementation didn't account for the case where a node had `nil` children. Please make a PR with this change 👍

**Comment by ShannonChenCHN** [comment]
@kelvinlauKL  

Really thanks for providing such a great sources for us to learn algorithm !!

But in the process of learning, I did meet some difficulties, as a beginner. So I just have a small suggestion, wish this could help more learners like me.

To be honest, it's really hard for me to understand the implementation of AVL Tree's rotation. Partly because it seems like our implementation here is different from the AVL Tree implementation in some other books, like *Data Structures and Algorithm Analysis in C (by Mark Allen Weiss)*.

Of course, this is OK.

**But if we could have more detail explanation (documentation or comments, diagram) for AVL Tree, especially the most important part, like rotation, we could make our code and our core theory easier to understood.  **

**Comment by kelvinlauKL** [comment]
Thanks for the suggestion! We have plans to deliver some polished content in the new year.
