### ISSUE TITLE
Correct way to start learning

### ISSUE THREAD

**Issue by jpv123** [raywenderlich/swift-algorithm-club#672]
Hi, I'm wondering if there is a list with a suggested order to start learning. Maybe start with linked lists, or dive in to algorithms right in the start and learn data structures after?

Thanks in advance

**Comment by kelvinlauKL** [comment]
Linked lists are a good topic to start on. When I studied in school, I started with data structures before moving to algorithms. Seemed to work well.

**Comment by jack3010** [comment]
@jpv123 You can learn these necessary things: 
- Read to know about Big O notation.
- Linked lists (How to build single linked list, doubly linked list, circular linked list?)
- Stack and Queue. ( How to build stack and queue base on the array?)
- Recursion. 
- Quick sort and Merge sort
- Hash Table 
- Breadth-first Search.
- Deep-first Search.
And don't forget let hand on it.
