### ISSUE TITLE
Shuffle Algorithm Issues

### ISSUE THREAD

**Issue by rlziii** [raywenderlich/swift-algorithm-club#673]
### Brief Intro

The Fisher-Yates / Knuth shuffle algorithm doesn't include the first index in the array and the swap() function should be changed to the swapAt method.

### More Details

The algorithm should include the first index of the array (index 0), which currently isn't accounted for (instead stopping at index 1).  Also, because of changes in Swift 4, when using the swap() function in this way, the following error occurs:

Simultaneous accesses to xxxxxxxx, but modification requires exclusive access

Therefore, I believe the following changes should be implemented as such:

```
extension Array {
  public mutating func shuffle() {
    for i in stride(from: count - 1, through: 0, by: -1) {
      let j = random(i + 1)
      if i != j {
        self.swapAt(i, j)
      }
    }
  }
}

**Comment by hollance** [comment]
You're correct about the swap but not about the array index. Read the article for why we stop at index 1.

**Comment by rlziii** [comment]
Thank you for the reply.  I misunderstood the need for accounting for index 0 and I see now why it isn't necessary.

**Comment by kelvinlauKL** [comment]
Closed as resolved.
