### ISSUE TITLE
Broken youtube link for splay trees

### ISSUE THREAD

**Issue by AamirAnwar** [raywenderlich/swift-algorithm-club#677]
### Brief Intro
Hey just noticed the youtube video at the end of the splay tree README has been removed
Splay Tree by University of California in Berkeley - CS 61B Lecture 34
https://www.youtube.com/watch?v=G5QIXywcJlY

### More Details
Probably best to replace it?

**Comment by kelvinlauKL** [comment]
Thanks for letting us know. We should either delete or change it.

**Comment by AamirAnwar** [comment]
I think we can put this link in it's stead
https://www.youtube.com/watch?v=8Zs1lj_bUV0
I can open a pull request with this change if it's cool 👍

**Comment by StephenClarkApps** [comment]
This should be an easy fix, someone open a pull request for this!!

**Comment by AamirAnwar** [comment]
Yup i was just waiting for someone to double check the link. Cool if i open a PR with this link??

**Comment by AamirAnwar** [comment]
Done -> https://github.com/raywenderlich/swift-algorithm-club/pull/704

**Comment by kelvinlauKL** [comment]
Closed because fix is done!
