### ISSUE TITLE
Pull requests

### ISSUE THREAD

**Issue by gringoireDM** [raywenderlich/swift-algorithm-club#690]
### Brief Intro

Pull requests. are they still reviewed/merged?

### More Details

Hi, I would like to know if there is still maintenance around the PR. I see a big list now waiting for reviews since long time. I opened a pull request myself that add the introsort algorithm (#684 ).

Thank you for any answer.

**Comment by kelvinlauKL** [comment]
Yeah, we're still here. Sorry for the inactivity. Vacations + prep for RWDevCon has us backlogged for a bit.
