### ISSUE TITLE
Public GitHub Pages?

### ISSUE THREAD

**Issue by aquarchitect** [raywenderlich/swift-algorithm-club#691]
### Brief Intro

Public GitHub Pages?

### More Details

@kelvinlauKL @vincentngo I wonder whether we can let everybody knows the web version on GitHub Pages under the repository description.

**Comment by kelvinlauKL** [comment]
Will do. Thanks for the reminder. On the next SAC update blog this month I’ll make a mention.

Thanks!

**Comment by aquarchitect** [comment]
Cool.
