### ISSUE TITLE
Broken internal link in README 

### ISSUE THREAD

**Issue by csknns** [raywenderlich/swift-algorithm-club#695]
In [Brute-Force String Search](https://github.com/raywenderlich/swift-algorithm-club/blob/master/Brute-Force%20String%20Search/README.markdown) the link to Boyer-Moore is broken it points to non existent [Boyer-Moore](https://github.com/raywenderlich/swift-algorithm-club/blob/master/Boyer-Moore) instead of [Boyer-Moore-Horspool](https://github.com/raywenderlich/swift-algorithm-club/tree/master/Boyer-Moore-Horspool)

**Comment by kelvinlauKL** [comment]
Thanks for the tip! Will follow up.
