### ISSUE TITLE
Rabin-Karp: How was this constant determined?

### ISSUE THREAD

**Issue by iluvcapra** [raywenderlich/swift-algorithm-club#713]
More of a question than an issue, really. I'm implementing my own version of this for binary searching and wonder if this constant was selected with the assumption that the search string would just be text.

https://github.com/raywenderlich/swift-algorithm-club/blob/898db6fd3f266812be8387a2b2478d5f072cf872/Rabin-Karp/rabin-karp.swift#L24

**Comment by billbarbour** [comment]
That was a typo.  The hash multiplier is used to help reduce the chance of a hash collision while calculating the hashes.  It is typically a large prime number, but not so large as to overflow your data structures.  My original intent was for that value to be 69061.

**Comment by iluvcapra** [comment]
Oh awesome, I was wondering why it wasn't prime.  I guess this is a defect ticket then!

**Comment by billbarbour** [comment]
Yup, ^ PR updates the code.  Thank you for catching this error!
