### ISSUE TITLE
Recommend describing how to run examples in Xcode or other environments

### ISSUE THREAD

**Issue by robert-dodier** [raywenderlich/swift-algorithm-club#719]
Hi, this collection seems like a very valuable resource, thanks very much for your efforts.

I've read the README, but it's not clear how to run the various projects in Xcode or in some other environment (e.g. command line). I'd like to recommend that in the README you give some advice about how to run the examples, in whatever way you think is most suitable. 

For the record, I imported swift-algorithm-club into Xcode using the "Clone an existing project" option. Xcode appears to automatically compile APSP but it complains "Could not launch APSP". I didn't try to investigate that. I looked for a way to run some of the other examples but things that I tried (double clicking or right clicking on what appear to be project files) didn't seem to have any effect.

Let me say a little about my situation, although I believe that this issue is more general. I have experience with software development, but not much with Xcode or Swift. So this project seems like a good way for me (and presumably others) to learn about programming on MacOS using Swift, since these algorithms are familiar from other contexts (school or work).

**Comment by kelvinlauKL** [comment]
Hey there,

The APSP workspace hasn't been properly maintained, so I'm not sure what's going on in there. However, if you open up the individual algorithms and run the playgrounds, there shouldn't be an issue.

**Comment by robert-dodier** [comment]
Thanks for your reply. After working a little bit more with Xcode + this project, I see now that there is an assumption that the user is going to use the code for the various subprojects in a certain way and not in some other way -- that is to say, there is an assumption built into the project. I recommend that this assumption be stated clearly in the readme.

Specifically what I see is that it is intended that the user will open the playground and then the code will run automatically, without further intervention by the user. However it took me several tries to figure that out. The right-pointing wedge at the top of the window, which is often interpreted as a "play" or "go" button, in fact interferes with running the code when the playground is open, as it tries to build another project (APSP) which is, I suppose, a project-wide default. Also, the playground file is not displayed with the .playground suffix, so it must be recognized from a tiny icon which is different from the other tiny icons.

I know that running the subprojects by opening the playground file is just the "right thing to do" which you'll automatically if you are familiar with Xcode. What I am recommending here is that you imagine the point of view of a person who is unfamiliar with Xcode, who won't know the "right thing", and put a sentence or two in the readme.
