### ISSUE TITLE
Finding intersection of two arrays of integers

### ISSUE THREAD

**Issue by nekonari** [raywenderlich/swift-algorithm-club#72]
This actually was asked by a hiring manager at Apple:

"Given two arrays with integers, find integers that are in both arrays."

And of course, there are:
1. Brute force (O(n^2)
2. Sort an array + Binary search (O(n log n))
3. Create hash table of one + find matches (O(n))

**Comment by hollance** [comment]
Hiring managers sure love hash table questions. :-)

**Comment by chris-pilcher** [comment]
Thanks for the question nekonari! Since this issue hasn't had any comments for 3 months I'm going to close it. Please feel free to raise new issues/ask questions 😄
