### ISSUE TITLE
GitHub Page

### ISSUE THREAD

**Issue by aquarchitect** [raywenderlich/swift-algorithm-club#720]
Hello @kelvinlauKL, 

Is there any chance that you can public GitHub Page's link in the repository's description? 

Thanks,

**Comment by kelvinlauKL** [comment]
Open up a PR and I'll gladly add it in! @aquarchitect!

**Comment by aquarchitect** [comment]
@kelvinlauKL, I am thinking of adding the link, [http://raywenderlich.github.io/swift-algorithm-club/](http://raywenderlich.github.io/swift-algorithm-club/), right to the repository's description like the screenshot I attached below.

<img width="1036" alt="screen shot 2018-06-06 at 8 45 08 am" src="https://user-images.githubusercontent.com/8365795/41049889-c55f9bda-6966-11e8-97df-31403a655dec.png">

Let me know what you think. If it is not possible, I can add the link to the README file in a PR.

**Comment by kelvinlauKL** [comment]
@aquarchitect I just checked out the link in Mojave dark mode, and I see this: 
<img width="985" alt="screen shot 2018-06-06 at 8 32 13 p m" src="https://user-images.githubusercontent.com/11384608/41076899-beae1174-69c8-11e8-93fd-30e6c8674c03.png">

I'm going to hold off adding that link on there. Would you know how to handle this?

**Comment by aquarchitect** [comment]
@kelvinlauKL I got no idea. The script relies on GitHub rendering engine to convert README to HTML. I don't have Mojave installed to test out myself, but do you have any trouble of viewing a readme document on Mojave?

**Comment by kelvinlauKL** [comment]
@aquarchitect The README is fine, but the generated html is behaving badly on Mojave.

**Comment by aquarchitect** [comment]
Hi @kelvinlauKL,

Can you view this link [https://aquarchitect.github.io/swift-algorithm-club/](https://aquarchitect.github.io/swift-algorithm-club/) if you still have the issue of dark background on Mojave? If it's good to go, I will create a PR.

Thanks.

**Comment by kelvinlauKL** [comment]
Roger. I'm at work on a non-Mojave computer, so I'll take a look once I get home. Thanks!

**Comment by aquarchitect** [comment]
Hi @kelvinlauKL, 

The issue of dark mode has been resolved itself in the official release of Mojave, and it requires no further action. 

However, regards to the original issue, I still would love to have the link to GitHub Page version of the repo publicly available under the description (please prefer to my [previous comment](https://github.com/raywenderlich/swift-algorithm-club/issues/720#issuecomment-395119889). It is a much nicer and better experience for everyone to enjoy these wonderful articles.

Thank you so much for considering my proposal.

**Comment by kelvinlauKL** [comment]
Hey @aquarchitect, I took another look at the GitHub page and it doesn't seem to be much of an improvement to the README files. 

For now I've added a reference to it to the README!
