### ISSUE TITLE
next?.previous referencing next itself

### ISSUE THREAD

**Issue by highborncow** [raywenderlich/swift-algorithm-club#722]
Shouldn't it be "next?.previous = list.last"? Since in the line before next was assigned to list.last?.next

https://github.com/raywenderlich/swift-algorithm-club/blob/bcdd28236d981f8763fdda9ebe41b699ea624579/Linked%20List/LinkedList.playground/Contents.swift#L179

**Comment by kelvinlauKL** [comment]
Great catch! I agree with what you said. 

Please make a PR and I'll merge that fix in 👍

**Comment by highborncow** [comment]
I may have done something wrong, I forgot to create a new branch and just committed my changes. Now I don't know how to make a pull request :D I'm a beginner in git, what should I do?

**Comment by kelvinlauKL** [comment]
@highborncow Here's a tutorial that outlines the steps you'll need to do:  https://www.raywenderlich.com/179717/open-source-collaboration-using-git-and-github

**Comment by highborncow** [comment]
I think I got it right this time, sorry it took so long, this is my first contribution to a git unrelated to my graduation or work. Thanks for the help.

**Comment by kelvinlauKL** [comment]
No worries. Thanks for noticing the mistake and applying the fix!
