### ISSUE TITLE
Add lapindrome checker

### ISSUE THREAD

**Issue by tbhaxor** [raywenderlich/swift-algorithm-club#728]
### Brief Intro

Add a new algorithm, to check if the string is lapindrome or not

#### What is lapindrome
```
Lapindrome is defined as a string which when split in the middle, gives two halves having the same characters and same frequency of each character.
```
**for example**
1. gaga
2. abccda
3. xyyx

**Comment by tbhaxor** [comment]
@gmotzespina YOU ARE RIGHT

**Comment by gmotzespina** [comment]
I think my PR hasn’t been merged

**Comment by tbhaxor** [comment]
@gmotzespina oh yes sorry bro

**Comment by kelvinlauKL** [comment]
Heyo,

I've added some comments to the PR for revisions. For now let's close this issue since there's already a  PR addressing this!
