### ISSUE TITLE
Linear Regression unexpected results

### ISSUE THREAD

**Issue by ProjectDent** [raywenderlich/swift-algorithm-club#734]
I wrote a test around the Linear Regression algorithm, which can be run in Xcode Playgrounds (I've included the Linear Regression algorithm at the top for convenience):

```
import UIKit

func average(_ input: [Double]) -> Double {
    return input.reduce(0, +) / Double(input.count)
}

func multiply(_ a: [Double], _ b: [Double]) -> [Double] {
    return zip(a,b).map(*)
}

func linearRegression(_ xs: [Double], _ ys: [Double]) -> (Double) -> Double {
    let sum1 = average(multiply(ys, xs)) - average(xs) * average(ys)
    let sum2 = average(multiply(xs, xs)) - pow(average(xs), 2)
    let slope = sum1 / sum2
    let intercept = average(ys) - slope * average(xs)
    return { x in intercept + slope * x }
}

let points = [
    CGPoint(x: 1, y: 2),
    CGPoint(x: 2, y: 1),
    CGPoint(x: 3, y: 4),
    CGPoint(x: 4, y: 3)
]

let xs = points.map({Double($0.x)})
let ys = points.map({Double($0.y)})

let regression = linearRegression(xs, ys)

let y1 = regression(1) //Result is 1.6
let y2 = regression(3) //Result is 2.8
```

I expected the results to be `1`, and `3`, respectively.

I've drawn a diagram of this, with points in blue, expected line in green, and actual line in yellow.

<img width="255" alt="screen shot 2018-08-13 at 17 35 16" src="https://user-images.githubusercontent.com/1865635/44046039-3ba76458-9f22-11e8-87fe-fd54f7dc8618.png">

**Comment by kelvinlauKL** [comment]
Verified this bug.

**Comment by kelvinlauKL** [comment]
@ProjectDent #737 addresses this problem. Mind if I ask you to review it?

**Comment by ProjectDent** [comment]
Asking on StackOverflow, their response was that my expectation that it should follow the green line was incorrect, and that the yellow line is an expected linear regression. The green line would be an orthogonal regression. They may have been wrong, however.

https://stackoverflow.com/questions/51826911/linear-regression-result-not-as-expected-following-simple-test

I think someone who understands this math well (and DenisLitvin may, I don't know his background) should verify that this change is correct first.

**Comment by hollance** [comment]
The formula used in this code appears to be the one from https://en.wikipedia.org/wiki/Ordinary_least_squares under "Simple linear regression model". The suggested fix does not appear to be correct because it really does need to be `multiply(xs, ys)` and not `multiply(xs, xs)`.

However, I'm not 100% sure the calls to `average(...)` in the original implementation are always correct, for example `pow(average(xs), 2)` is not the same as `1/n * pow(sum(xs), 2)`. It's possible these extra factors of `1/n` cancel out, though -- I haven't verified the actual math...

**Comment by hollance** [comment]
FWIW, I think the diagram in this bug report is wrong. The yellow line does not plot the actual output from the given algorithm.

I ran the linear regression in Mathematica on the exact same 4 points and got the exact same answer as the original Swift implementation:

<img width="636" alt="screen shot 2018-08-17 at 14 51 55" src="https://user-images.githubusercontent.com/346853/44267132-5b130000-a22d-11e8-921a-963c38e187ec.png">

Note how the intercept is 1 and the slope is 0.6. If you print these values inside `linearRegression()` you'll also get 1 for the intercept and 0.6 for the slope.
