### ISSUE TITLE
Description of the complexity of solution 1 of the Two-Sum Problem

### ISSUE THREAD

**Issue by pstoehr** [raywenderlich/swift-algorithm-club#738]
It is mentioned that the complexity of the first solution is O(n) based on the fact that each element of the array is just accessed once. But for a worst case scenario all elements of the array might be added to the dictionary and it might be checked for all elements whether they are in the dictionary or not.

Is there a guaranty that inserting and testing for existence of an element in a dictionary is an O(1) algorithm? If "yes" this should be mentioned!

**Comment by kelvinlauKL** [comment]
Hey @pstoehr! 

Inserting and testing for the existence of an element in dictionary is indeed `O(1)`. You can find performance of standard library types in the [official docs](https://developer.apple.com/documentation/swift/dictionary).
