### ISSUE TITLE
Ternary Search Tree

### ISSUE THREAD

**Issue by Satre95** [raywenderlich/swift-algorithm-club#83]
Currently working on this.
- [x] Create TST with insertion and find supported
- [x] Document source code
- [ ] Write README explaining the data structure, its uses, and its pros and cons.

**Comment by kelvinlauKL** [comment]
Hey @Satre95, how's this coming along?

**Comment by Satre95** [comment]
Hi @kelvinlauKL 
Sorry about this, I got busy with college and and totally dropped the ball. The TST itself is completely operational, and I have written documentation comments, but the README and description docs need to be written.

**Comment by kelvinlauKL** [comment]
Thanks @Satre95!

Just checking in. We're in the process of cleaning up the inactive issues to make room for new contributions. Are you still interested in writing it?

**Comment by Satre95** [comment]
I am. I will be done with classes in another week, so I can write the README then
