### ISSUE TITLE
BoundedPriorityQueue confusion

### ISSUE THREAD

**Issue by hollance** [raywenderlich/swift-algorithm-club#85]
Hey @johnsgill3,

I was trying to clean up your BoundedPriorityQueue a little but now I'm horribly confused...

Is this supposed to be a min- or max-priority queue? From the description I gathered it was a min-priority queue, so the item with the lowest priority value would be the most important and therefore be at the front of the queue.

However, in the implementation the item with the highest priority is at the front of the queue. When you dequeue() it always returns the highest priority item. So that leads me to believe it's a max-priority queue.

The confusing thing is this: when the queue gets full, you call dequeue() to throw away the least important item. But that actually throws away the most important item!

What am I missing here?

**Comment by hollance** [comment]
Here is my implementation of BPQ using a linked list: https://gist.github.com/hollance/774fa4918d699f18958a

It's a max-priority queue. If you insert an item when the queue is full, it drops the one with the lowest priority.

Is this what you had in mind?

**Comment by chris-pilcher** [comment]
The implementation of BPQ was updated in #124.
