### ISSUE TITLE
Add bit shift operations to BitSet

### ISSUE THREAD

**Issue by Heraldk** [raywenderlich/swift-algorithm-club#850]
### Brief Intro

I used the BitSet class from this repository as part of an Advent of Code puzzle this year. For the puzzle I required bit shifting operations (<< and >>) so I implemented these. I figured it might be of interest to share back to the algorithm club.

### More Details

You can see my implementation in my fork here: https://github.com/Heraldk/swift-algorithm-club/commit/a2953343f16129995f90cfc6cf49236b3bcb9ae5

If you like it I can submit a pull request.

**Comment by richard-ash** [comment]
Yea that'd be great thanks! Looking forward to reading the PR 😃

**Comment by Heraldk** [comment]
Cool :) PR open.

**Comment by jrtibbetts** [comment]
I don't see a PR for this; I just see a link to a specific commit by @Heraldk.

**Comment by Heraldk** [comment]
PR here: https://github.com/raywenderlich/swift-algorithm-club/pull/855

**Comment by kelvinlauKL** [comment]
Closed because merged!
