### ISSUE TITLE
LRUCache and LinkedList have got out of sync

### ISSUE THREAD

**Issue by simoncozens** [raywenderlich/swift-algorithm-club#859]
### Brief Intro

LRUCache no longer compiles due (I think) to changes in LinkedList.

### More Details

Here's the `insert` method of `LRUCache`:

```swift
    private func insert(_ key: KeyType, val: Any) {
        cache[key] = val
        priority.insert(key, atIndex: 0)
        guard let first = priority.first else {
            return
        }
        key2node[key] = first
    }
```

I am getting two errors, one at the `priority.insert` line: "Argument labels '(_:, atIndex:)' do not match any available overloads". This is because LinkedList's `insert` has this signature:

```swift
    public func insert(_ value: T, at index: Int) {
```

Well, I can fix that by replacing `atIndex` with `at`.

But with the `key2node[key] = first` line gives me this error: "Cannot assign value of type 'KeyType' to type 'LinkedList<KeyType>.LinkedListNode<KeyType>?'"

I am not sure what the right fix is here. `priority.first` returns a value, not a node, but the assignment is expecting to store nodes. Should it even be `first` on a LinkedList or should it call `head` instead?

**Comment by richard-ash** [comment]
Thanks for flagging this! I just pulled the lastest and LRUCache seems to compile ok. Do you mind rebasing from master and trying to again? 

Also, note that LRUCache comes with its own implementation of LinkedList, you can find it under `LRUCache.playground/Sources/LinkedList.swift`.

Hope this has been helpful 😄Let me know if there's more I can do to assist

**Comment by simoncozens** [comment]
OK, so the problem is that LinkedList and LinkedList have gotten out of sync! LRUCache's "own implementation" of LinkedList has different signatures to the LinkedList implementation; LRUCache compiles if you use its own bundled (old) version of LinkedList in a project, but not if you use the one from the LinkedList directory. What I did was grab the `LRUCache.swift` file from LRUCache, find that it depended on LinkedList, and so grabbed `LinkedList.swift` from the LinkedList directory.

I would have thought it would make more sense for modules which build on other modules to be tracking the latest implementation of those modules rather than bundling their own - or if they do bundle their own, making sure that implementation is the latest - but I can see that what you have compiles if you use it in a standalone way. (Of course, a project which first pulled in LinkedList for something else and then tried to pull in LRUCache would also fail to compile...)

What do you think? (As it happens I no longer need this, because rather than building my own LRUCache for images I have just used SDWebImage instead...)

**Comment by inekipelov** [comment]
````
#~~~~
````

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
