### ISSUE TITLE
Wrong description and typo.

### ISSUE THREAD

**Issue by bbvch13531** [raywenderlich/swift-algorithm-club#861]
### Brief Intro

There is wrong description in Linked List and typo in Insertion Sort.

### More Details

In LinkedList.swift
line 70
`assert(index >= 0, "index must be greater than 0")`

This should changed to index must be greater or equal to 0

In InsertionSort.swift
line 25
/// - Parameter array: the array to be sorted, conatining elements that conform to the Comparable protocol

`conatining` is a typo.

I'll fix it and send PR. 😄

**Comment by richard-ash** [comment]
Great find, thanks again!
