### ISSUE TITLE
Create a Swift Benchmark from BucketSort 

### ISSUE THREAD

**Issue by rajbarik** [raywenderlich/swift-algorithm-club#863]
Recently I worked on the ExistentialSpecializer optimization in the Swift compiler (https://github.com/apple/swift/pull/19820, others). BucketSort seems to improve significantly with this optimization. BucketSort has nice protocol usages and I was wondering if it makes sense to make it a Swift performance benchmark. What are the licensing and other issues? Any thoughts?

**Comment by kelvinlauKL** [comment]
We operate under MIT, so you're free to use anything here =)
