### ISSUE TITLE
Return type of BinarySearchTree.predecessor is necessary?

### ISSUE THREAD

**Issue by bbvch13531** [raywenderlich/swift-algorithm-club#865]
### Brief Intro

predecessor, successor function in BinarySearchTree

```
public func predecessor() -> BinarySearchTree<T>?
public func successor() -> BinarySearchTree<T>?
```
Is `BinarySearchTree<T>?` necessary? I think `BinarySearchTree?` will fine.
If `BinarySearchTree<T>?` is necessary, would you please let me know the reason why?
If not, I take this issue and make PR. 
Thanks 😄 .

**Comment by kelvinlauKL** [comment]
Probably. The author may have forgotten the briefer version. Feel free to make the correction if the compiler agrees with you 👍
