### ISSUE TITLE
Optimized Queue doesn't seem to be more efficient than standard Queue

### ISSUE THREAD

**Issue by tedbrosby** [raywenderlich/swift-algorithm-club#910]
### Brief Intro

Queue-Optimized.swift uses the `Sequence` function called `contains` to confirm a safe existence of an Index before retrieving the element at the front of the Queue.  

### More Details

```swift  
subscript(guarded idx: Int) -> Element? {
    guard (startIndex..<endIndex).contains(idx) else {
        return nil
    }
    return self[idx]
}
```  
The problem is, `contains` is an O(N) operation over the total amount of the Indexes, meaning that Dequeue went from O(N) to O(M) where M is the space complexity of the Index as Integer.  
  
https://github.com/apple/swift/blob/d6eebe9faa16c19de0502156f6a453a9020208b8/stdlib/public/core/SequenceAlgorithms.swift#L547-L573  
  
I think it can be possible to have the desired efficiency if the Array extension is removed and a private Bool is created that determines if head is <= safeEnd (an Int that gets increased whenever a value is appended to the array) and two Int values that are determined when values are enqueued or when the Array shift operation takes place are calculated, and head is checked against these two Int values. What do you think?  
  
```swift 
fileprivate var safeStart: Int = 0 
fileprivate var safeEnd: Int = 0  
public mutating func dequeue() -> T? {
    guard isSafe(idx: head),
        let element = array[head] else { return nil }

    array[head] = nil
    head += 1

    let percentage = Double(head)/Double(array.count)
    if array.count > 50 && percentage > 0.25 {
      array.removeFirst(head)
      safeEnd -= head
      head = 0
    }

    return element
}
private func isSafe(idx: Int) -> Bool {
    return idx >= safeStart && idx <= safeEnd
  }  
```

**Comment by kelvinlauKL** [comment]
Hey, thanks for the suggestion! I see what you're getting at there.

Like you stated, the `contains` method defined by `Sequence` is O(n) by default. However, types can override the default behaviour. In the case of the `Range` type, I wonder if they specialized the `contains` method to give `O(1)` performance. 

`Range` requires the values to be `Comparable` and `Strideable`, which means they could very well specialize the `contains` method to simply:

```
func contains(_ value: T) -> Bool {
  value >= lowerBound && value < upperBound
}
```

I feel this case is very likely.

**Comment by kelvinlauKL** [comment]
That seems to be the case! Source: https://github.com/apple/swift/blob/da61cc8cdf7aa2bfb3ab03200c52c4d371dc6751/stdlib/public/core/Range.swift#L166

Closing this as resolved, but feel free to reopen if you still feel there's an issue!
