### ISSUE TITLE
When creating playgrounds do not copy and past the swift files inside the playground

### ISSUE THREAD

**Issue by barbaramartina** [raywenderlich/swift-algorithm-club#97]
Hi guys, I've seem some of the algorithms are copy-pasting the code inside the playgrounds in order to access to it. For example [Bloom Filter](https://github.com/hollance/swift-algorithm-club/blob/master/Bloom%20Filter/BloomFilter.playground/Contents.swift).

I'd say it's better to include the files we develop for the algorithms inside the playground's sources folder.

This can be achieved doing this [Apple recommended steps to add auxiliary code to your playgrounds](https://developer.apple.com/library/ios/recipes/Playground_Help/Chapters/AddAuxilliaryCodetoaPlayground.html).

This option still has the limitation that the changes made on the original file are not reflected inside the playground's sources folder. But I think it's cleaner than copying all the source code inside the playground itself. 
The changes are not reflected because the file is actually duplicated not referenced.
If somebody knows how to reflect the changes you made on the original file inside the playground please let me know. 
I have been trying creating symbolic links for the command line but this is not working.

**Comment by hollance** [comment]
A lot of the algorithms already do this but not all of them. Personally, I've been putting the algorithm in the playground's Sources folder if it's kinda big but if it's only a few lines then I put it directly into the playground.

Unfortunately, it means copy-pasting between the .swift file and the playground by hand if you make any changes.

**Comment by armcknight** [comment]
There's an alternative: put all the algorithm related stuff into a framework target, and import the module in the playground. Then, place the xcodeproj that builds the framework into an xcworkspace with the playground at the sibling level. This eliminates all duplication. Check out the all-pairs shortest paths project to see what I mean if it's unclear.
