### ISSUE TITLE
Efficiency of LinkedList.count

### ISSUE THREAD

**Issue by MattGeimer** [raywenderlich/swift-algorithm-club#974]
https://github.com/raywenderlich/swift-algorithm-club/blob/5d551049a02cccd00b046937750fd6d736065f76/Linked%20List/LinkedList.swift#L38-L50

Isn't this solution less efficient than having a stored property? The current implementation of `count` seems to be O(n), but can be reduced to O(1) by incrementing or decrementing the value when performing modification operations. For example, the following code will iterate through the while loop in `count` 28 times:

```
var myList = LinkedList(array: Array<Int>(0 ..< 10))

print(myList.count)

myList.append(myList.count)

print(myList.count)
```

**Comment by hollance** [comment]
Yes you are correct that this way of keeping the count is inefficient. The LinkedList article points this out too. :-)

**Comment by MattGeimer** [comment]
Probably should have noticed the note 🙃. Is there any particular reason this implementation is preferred?

**Comment by hollance** [comment]
Keep in mind that this repo is about explaining how algorithms work, not to give the most efficient implementations possible. So it's useful to demonstrate how to grab the count by iterating through the entire list.
