### ISSUE TITLE
Adding Wikibook Algorithms Implemention book to the main README

### ISSUE THREAD

**Issue by barbaramartina** [raywenderlich/swift-algorithm-club#99]
I've found a [book on Wikibooks about algorithms implementation](https://en.wikibooks.org/wiki/Algorithm_Implementation), which I think it's worthy to include in the main README.
The goals of the book is to collect several algorithms and documentation, it's unifying information from wiki articles and wiki source code.
Let me know what do you think about the book, and I'd add it to the main README.

**Comment by hollance** [comment]
Sure, feel free to add it to the readme. More links is better! :-)

**Comment by barbaramartina** [comment]
great!

**Comment by kelvinlauKL** [comment]
This has since been added, so I'm closing this issue to clean this repo up a bit! Thanks @barbaramartina
